#pragma once

#ifndef CVENUMS_h
#define CVENUMS_h

// enums.h

#include "CvDefines.h"

enum DllExport GameStateTypes
{
	GAMESTATE_ON,
	GAMESTATE_OVER,
	GAMESTATE_EXTENDED,
};

enum DllExport PopupStates
{
	POPUPSTATE_IMMEDIATE,
	POPUPSTATE_QUEUED,
	POPUPSTATE_MINIMIZED,
};

enum DllExport PopupEventTypes
{
	POPUPEVENT_NONE,
	POPUPEVENT_PRODUCTION,
	POPUPEVENT_WARNING,
	POPUPEVENT_CIVIC,
};

enum DllExport CameraLookAtTypes
{
	CAMERALOOKAT_NORMAL,
	CAMERALOOKAT_CITY_ZOOM_IN,
	CAMERALOOKAT_BATTLE,
	CAMERALOOKAT_BATTLE_ZOOM_IN,
	CAMERALOOKAT_SHRINE_ZOOM_IN,
	CAMERALOOKAT_IMMEDIATE,
	CAMERALOOKAT_HOTSEAT,
};

enum DllExport CameraMovementSpeeds
{
	CAMERAMOVEMENTSPEED_NORMAL,
	CAMERAMOVEMENTSPEED_SLOW,
	CAMERAMOVEMENTSPEED_FAST,
};

enum DllExport ZoomLevelTypes
{
	ZOOM_UNKNOWN							= 0x00000000,
	ZOOM_DETAIL								= 0x00000001,
	ZOOM_NORMAL								= 0x00000002,
	ZOOM_GLOBEVIEW_TRANSITION	= 0x00000004,
	ZOOM_GLOBEVIEW						= 0x00000008
};

enum DllExport ResourceLayerOptions
{
	RESOURCE_LAYER_NATIVE_TRADE,
	RESOURCE_LAYER_NATIVE_TRAIN,
	RESOURCE_LAYER_RESOURCES,

#ifdef _USRDLL
	NUM_RESOURCE_LAYERS,
#endif
};

enum DllExport UnitLayerOptionTypes
{
	SHOW_ALL_MILITARY,
	SHOW_TEAM_MILITARY,
	SHOW_ENEMIES_IN_TERRITORY,
	SHOW_ENEMIES,
	SHOW_PLAYER_DOMESTICS,

#ifdef _USRDLL
	NUM_UNIT_LAYER_OPTION_TYPES
#endif
};


enum DllExport PlotIndicatorVisibilityFlags
{
	VISIBLE_ALWAYS,
	VISIBLE_ONSCREEN_ONLY,
	VISIBLE_OFFSCREEN_ONLY,
	VISIBLE_ONGLOBE_ONLY,
	VISIBLE_NEVER
};


enum DllExport DirectionTypes
{
	NO_DIRECTION = -1,

	DIRECTION_NORTH,
	DIRECTION_NORTHEAST,
	DIRECTION_EAST,
	DIRECTION_SOUTHEAST,
	DIRECTION_SOUTH,
	DIRECTION_SOUTHWEST,
	DIRECTION_WEST,
	DIRECTION_NORTHWEST,

#ifdef _USRDLL
	NUM_DIRECTION_TYPES,
#endif

	DIRECTION_NORTH_MASK = 1 << DIRECTION_NORTH,
	DIRECTION_NORTHEAST_MASK = 1 << DIRECTION_NORTHEAST,
	DIRECTION_EAST_MASK = 1 << DIRECTION_EAST,
	DIRECTION_SOUTHEAST_MASK = 1 << DIRECTION_SOUTHEAST,
	DIRECTION_SOUTH_MASK = 1 << DIRECTION_SOUTH,
	DIRECTION_SOUTHWEST_MASK = 1 << DIRECTION_SOUTHWEST,
	DIRECTION_WEST_MASK = 1 << DIRECTION_WEST,
	DIRECTION_NORTHWEST_MASK = 1 << DIRECTION_NORTHWEST,
};

enum DllExport CardinalDirectionTypes
{
	NO_CARDINALDIRECTION = -1,

	CARDINALDIRECTION_NORTH,
	CARDINALDIRECTION_EAST,
	CARDINALDIRECTION_SOUTH,
	CARDINALDIRECTION_WEST,

#ifdef _USRDLL
	NUM_CARDINALDIRECTION_TYPES
#endif
};

enum DllExport RotationTypes
{
	ROTATE_NONE = 0,
	ROTATE_90CW,
	ROTATE_180CW,
	ROTATE_270CW,
	NUM_ROTATION_TYPES,

	ROTATE_NONE_MASK	= 1 << ROTATE_NONE,
	ROTATE_90CW_MASK	= 1 << ROTATE_90CW,
	ROTATE_180CW_MASK	= 1 << ROTATE_180CW,
	ROTATE_270CW_MASK	= 1 << ROTATE_270CW,
};

// camera wrap helper
enum DllExport WrapDirection
{
	WRAP_SAVE,
	WRAP_NONE = WRAP_SAVE,
	WRAP_RESTORE,
	WRAP_LEFT,
	WRAP_RIGHT,
	WRAP_UP,
	WRAP_DOWN,

#ifdef _USRDLL
	NUM_WRAP_DIRECTIONS,
#endif

	WRAP_LEFT_MASK = 1 << WRAP_LEFT,
	WRAP_RIGHT_MASK = 1 << WRAP_RIGHT,
	WRAP_UP_MASK = 1 << WRAP_UP,
	WRAP_DOWN_MASK = 1 << WRAP_DOWN,
};

enum DllExport ColorTypes
{
	NO_COLOR = -1,
};

enum DllExport PlayerColorTypes
{
	NO_PLAYERCOLOR = -1,
};

//Warning: these values correspond to locations in the plot texture [JW]
enum DllExport PlotStyles
{
	PLOT_STYLE_NONE = -1,

	//first row
	PLOT_STYLE_NUMPAD_1 = 0,
	PLOT_STYLE_NUMPAD_2,
	PLOT_STYLE_NUMPAD_3,
	PLOT_STYLE_NUMPAD_4,
	PLOT_STYLE_NUMPAD_6,
	PLOT_STYLE_NUMPAD_7,
	PLOT_STYLE_NUMPAD_8,
	PLOT_STYLE_NUMPAD_9,

	//second row
	PLOT_STYLE_NUMPAD_1_ANGLED = 8,
	PLOT_STYLE_NUMPAD_2_ANGLED,
	PLOT_STYLE_NUMPAD_3_ANGLED,
	PLOT_STYLE_NUMPAD_4_ANGLED,
	PLOT_STYLE_NUMPAD_6_ANGLED,
	PLOT_STYLE_NUMPAD_7_ANGLED,
	PLOT_STYLE_NUMPAD_8_ANGLED,
	PLOT_STYLE_NUMPAD_9_ANGLED,

	//third row
	PLOT_STYLE_BOX_FILL = 16,
	PLOT_STYLE_BOX_OUTLINE,
	PLOT_STYLE_RIVER_SOUTH,
	PLOT_STYLE_RIVER_EAST,
	PLOT_STYLE_SIDE_ARROWS,
	PLOT_STYLE_CIRCLE,
	PLOT_STYLE_TARGET,
	PLOT_STYLE_DOT_TARGET,

	//fourth row
	PLOT_STYLE_WAVES = 24,
	PLOT_STYLE_DOTS,
	PLOT_STYLE_CIRCLES,
};

//Warning: these values are used as an index into a fixed array
enum DllExport PlotLandscapeLayers
{
	PLOT_LANDSCAPE_LAYER_ALL = -1,
	PLOT_LANDSCAPE_LAYER_BASE = 0,
	PLOT_LANDSCAPE_LAYER_RECOMMENDED_PLOTS = 1,
	PLOT_LANDSCAPE_LAYER_NUMPAD_HELP = 2,
	PLOT_LANDSCAPE_LAYER_REVEALED_PLOTS = 1,
};

enum DllExport AreaBorderLayers
{
	AREA_BORDER_LAYER_REVEALED_PLOTS,
	AREA_BORDER_LAYER_WORLD_BUILDER,
	AREA_BORDER_LAYER_FOUNDING_BORDER,
	AREA_BORDER_LAYER_CITY_RADIUS,
	AREA_BORDER_LAYER_RANGED,
	AREA_BORDER_LAYER_HIGHLIGHT_PLOT,
	AREA_BORDER_LAYER_EUROPE,
	NUM_AREA_BORDER_LAYERS
};

enum DllExport EffectTypes
{
	NO_EFFECT = -1,
};

enum DllExport AttachableTypes
{
	NO_ATTACHABLE = -1,
};

enum DllExport InterfaceModeTypes
{
	NO_INTERFACEMODE = -1,

	INTERFACEMODE_SELECTION,
	INTERFACEMODE_PING,
	INTERFACEMODE_SIGN,
	INTERFACEMODE_GRIP,
	INTERFACEMODE_GLOBELAYER_INPUT,
	INTERFACEMODE_GO_TO,
	INTERFACEMODE_GO_TO_TYPE,
	INTERFACEMODE_GO_TO_ALL,
	INTERFACEMODE_ROUTE_TO,
	INTERFACEMODE_PYTHON_PICK_PLOT,
	INTERFACEMODE_SAVE_PLOT_NIFS,

#ifdef _USRDLL
	NUM_INTERFACEMODE_TYPES
#endif
};

enum DllExport InterfaceMessageTypes
{
	NO_MESSAGE_TYPE = -1,

	MESSAGE_TYPE_INFO,
	MESSAGE_TYPE_LOG_ONLY,
	MESSAGE_TYPE_DISPLAY_ONLY,
	MESSAGE_TYPE_MAJOR_EVENT,
	MESSAGE_TYPE_MINOR_EVENT,
	MESSAGE_TYPE_CHAT,
	MESSAGE_TYPE_COMBAT_MESSAGE,
	MESSAGE_TYPE_QUEST,
	MESSAGE_TYPE_TUTORIAL,

#ifdef _USRDLL
	NUM_INTERFACE_MESSAGE_TYPES
#endif
};

enum DllExport FlyoutTypes
{
	NO_FLYOUT = -1,

	FLYOUT_HURRY,
	FLYOUT_TRAIN,
	FLYOUT_CONSTRUCT,
	FLYOUT_CONVINCE,
	FLYOUT_MOVE_TO,
	FLYOUT_SELECT_UNIT,
	FLYOUT_SELECT_ALL,
	FLYOUT_WAKE_ALL,
	FLYOUR_FORTIFY_ALL,
	FLYOUR_SLEEP_ALL,
};

enum DllExport MinimapModeTypes
{
	NO_MINIMAPMODE = -1,

	MINIMAPMODE_TERRITORY,
	MINIMAPMODE_TERRAIN,
	MINIMAPMODE_REPLAY,
	MINIMAPMODE_MILITARY,

#ifdef _USRDLL
	NUM_MINIMAPMODE_TYPES
#endif
};

enum DllExport EngineDirtyBits
{
	GlobeTexture_DIRTY_BIT,
	GlobePartialTexture_DIRTY_BIT,
	MinimapTexture_DIRTY_BIT,
	CultureBorders_DIRTY_BIT,

#ifdef _USRDLL
	NUM_ENGINE_DIRTY_BITS
#endif
};

enum DllExport InterfaceDirtyBits
{
	SelectionCamera_DIRTY_BIT,
	Fog_DIRTY_BIT,
	GlobeLayer_DIRTY_BIT,
	GlobeInfo_DIRTY_BIT,
	Waypoints_DIRTY_BIT,
	MiscButtons_DIRTY_BIT,
	PlotListButtons_DIRTY_BIT,
	SelectionButtons_DIRTY_BIT,
	CitizenButtons_DIRTY_BIT,
	Event_DIRTY_BIT,
	Center_DIRTY_BIT,
	GameData_DIRTY_BIT,
	Score_DIRTY_BIT,
	TurnTimer_DIRTY_BIT,
	Help_DIRTY_BIT,
	MinimapSection_DIRTY_BIT,
	SelectionSound_DIRTY_BIT,
	Cursor_DIRTY_BIT,
	CityInfo_DIRTY_BIT,
	UnitInfo_DIRTY_BIT,
	Popup_DIRTY_BIT,
	CityScreen_DIRTY_BIT,
	InfoPane_DIRTY_BIT,
	Flag_DIRTY_BIT,
	HighlightPlot_DIRTY_BIT,
	ColoredPlots_DIRTY_BIT,
	Financial_Screen_DIRTY_BIT,
	Foreign_Screen_DIRTY_BIT,
	Soundtrack_DIRTY_BIT,
	Domestic_Advisor_DIRTY_BIT,
	Advanced_Start_DIRTY_BIT,
	EuropeScreen_DIRTY_BIT,
	ResourceTable_DIRTY_BIT,
	///Tks Med
	NewYieldAvailable_DIRTY_BIT,
	///Tke

#ifdef _USRDLL
	NUM_INTERFACE_DIRTY_BITS
#endif
};
enum DllExport WidgetTypes
{
	WIDGET_PLOT_LIST,
	WIDGET_PLOT_LIST_SHIFT,
	WIDGET_CITY_SCROLL,
	WIDGET_LIBERATE_CITY,
	WIDGET_CITY_NAME,
	WIDGET_UNIT_NAME,
	WIDGET_CREATE_GROUP,
	WIDGET_DELETE_GROUP,
	WIDGET_TRAIN,
	WIDGET_CONSTRUCT,
	WIDGET_CONVINCE,
	WIDGET_HURRY,
	WIDGET_PLAYER_HURRY,
	WIDGET_MENU_ICON,
	WIDGET_ACTION,
	WIDGET_CITIZEN,
	WIDGET_CONTACT_CIV,
	WIDGET_SCORE_BREAKDOWN,
	WIDGET_ZOOM_CITY,
	WIDGET_END_TURN,
	WIDGET_AUTOMATE_CITIZENS,
	WIDGET_AUTOMATE_PRODUCTION,
	WIDGET_EMPHASIZE,
	WIDGET_DIPLOMACY_RESPONSE,
	WIDGET_GENERAL,
	WIDGET_FILE_LISTBOX,
	WIDGET_FILE_EDITBOX,
	WIDGET_WB_UNITNAME_EDITBOX,
	WIDGET_WB_CITYNAME_EDITBOX,
	WIDGET_WB_SAVE_BUTTON,
	WIDGET_WB_LOAD_BUTTON,
	WIDGET_WB_ALL_PLOTS_BUTTON,
	WIDGET_WB_LANDMARK_BUTTON,
	WIDGET_WB_ERASE_BUTTON,
	WIDGET_WB_EXIT_BUTTON,
	WIDGET_WB_UNIT_EDIT_BUTTON,
	WIDGET_WB_CITY_EDIT_BUTTON,
	WIDGET_WB_NORMAL_PLAYER_TAB_MODE_BUTTON,
	WIDGET_WB_NORMAL_MAP_TAB_MODE_BUTTON,
	WIDGET_WB_REVEAL_TAB_MODE_BUTTON,
	WIDGET_WB_DIPLOMACY_MODE_BUTTON,
	WIDGET_WB_REVEAL_ALL_BUTTON,
	WIDGET_WB_UNREVEAL_ALL_BUTTON,
	WIDGET_WB_REGENERATE_MAP,
	WIDGET_TRADE_ITEM,
	WIDGET_UNIT_MODEL,
	WIDGET_POPUP_QUEUE,

	//	This is meant for python buttons, it will call python functions for display and execution
	WIDGET_PYTHON,

	//	This button type is reserved for widgets meant to be displayed only.  This is meant for general interface text and such...
	WIDGET_HELP_DEFENSE,
	WIDGET_HELP_POPULATION,
	WIDGET_HELP_REBEL,
	WIDGET_HELP_GREAT_GENERAL,
	WIDGET_HELP_SELECTED,
	WIDGET_HELP_YIELD,
	WIDGET_HELP_PROMOTION,
	WIDGET_HELP_UNIT_PROMOTION,

	WIDGET_CHOOSE_EVENT,
	WIDGET_PEDIA_JUMP_TO_UNIT,
	WIDGET_PEDIA_JUMP_TO_PROFESSION,
	WIDGET_PEDIA_JUMP_TO_BUILDING,
	WIDGET_PEDIA_BACK,
	WIDGET_PEDIA_FORWARD,
	WIDGET_PEDIA_JUMP_TO_BONUS,
	WIDGET_PEDIA_MAIN,
	WIDGET_PEDIA_JUMP_TO_PROMOTION,
	WIDGET_PEDIA_JUMP_TO_IMPROVEMENT,
	WIDGET_PEDIA_JUMP_TO_CIVIC,
	WIDGET_PEDIA_JUMP_TO_CIV,
	WIDGET_PEDIA_JUMP_TO_LEADER,
	WIDGET_PEDIA_JUMP_TO_TERRAIN,
	WIDGET_PEDIA_JUMP_TO_YIELDS,
	WIDGET_PEDIA_JUMP_TO_FEATURE,
	WIDGET_PEDIA_JUMP_TO_FATHER,
	WIDGET_TURN_EVENT,
	WIDGET_PEDIA_DESCRIPTION,
	WIDGET_PEDIA_DESCRIPTION_NO_HELP,
	WIDGET_DEAL_KILL,
	WIDGET_MINIMAP_HIGHLIGHT,
	WIDGET_PRODUCTION_MOD_HELP,
	WIDGET_LEADERHEAD,
	WIDGET_LEADER_LINE,
	WIDGET_CLOSE_SCREEN,
	WIDGET_GLOBELAYER,
	WIDGET_GLOBELAYER_OPTION,
	WIDGET_GLOBELAYER_TOGGLE,
	WIDGET_CITY_UNIT_ASSIGN_PROFESSION,
	WIDGET_MOVE_CARGO_TO_CITY,
	WIDGET_RECEIVE_MOVE_CARGO_TO_CITY,
	WIDGET_MOVE_CARGO_TO_TRANSPORT,
	WIDGET_RECEIVE_MOVE_CARGO_TO_TRANSPORT,
	WIDGET_CREATE_TRADE_ROUTE,
	WIDGET_EDIT_TRADE_ROUTE,
	WIDGET_YIELD_IMPORT_EXPORT,
	WIDGET_ASSIGN_CITIZEN_TO_PLOT,
	WIDGET_ASSIGN_TRADE_ROUTE,
	WIDGET_EJECT_CITIZEN,
	WIDGET_SHIP_CARGO,
	WIDGET_DOCK,
	WIDGET_SAIL,
	WIDGET_GOTO_CITY,
	///TKs Med TradeRoutes
	WIDGET_TRADE_SCREEN_ROUTE,
	WIDGET_AUTO_TRADE_SCREEN,
	WIDGET_POP_UP_SCREEN,
	WIDGET_INVENTORS_HOUSE,
	WIDGET_CIVIC_HELP,
	WIDGET_PEDIA_JUMP_TO_TECHNOLOGY,
	//TK Tax
	WIDGET_TAX_ADVISOR,
    WIDGET_ARMORSMITH,
    WIDGET_MARKET,
	//TKe
	///TKe
	// Teacher List - start - Nightinggale
	WIDGET_TEACHER_LIST,
	WIDGET_HELP_TEACHER_UNIT,
	// Teacher List - end - Nightinggale
	// R&R, Robert Surcouf, Custom House Popup-Screen START
	WIDGET_CUSTOM_HOUSE,
	WIDGET_DOMESTIC_MARKET,
	// R&R, Robert Surcouf, Custom House Popup-Screen END

#ifdef _USRDLL
	NUM_WIDGET_TYPES
#endif
};

enum DllExport ButtonPopupTypes
{
	BUTTONPOPUP_TEXT,
	BUTTONPOPUP_MAIN_MENU,
	BUTTONPOPUP_CONFIRM_MENU,
	BUTTONPOPUP_DECLAREWARMOVE,
	BUTTONPOPUP_CONFIRMCOMMAND,
	BUTTONPOPUP_CONFIRMTASK,
	BUTTONPOPUP_LOADUNIT,
	BUTTONPOPUP_LOAD_CARGO,
	BUTTONPOPUP_LEADUNIT,
	BUTTONPOPUP_RAZECITY,
	BUTTONPOPUP_CHOOSEPRODUCTION,
	BUTTONPOPUP_CHOOSE_YIELD_BUILD,
	BUTTONPOPUP_CHOOSE_EDUCATION,
	BUTTONPOPUP_ALARM,
	BUTTONPOPUP_DEAL_CANCELED,
	BUTTONPOPUP_PYTHON,
	BUTTONPOPUP_FEAT,
	BUTTONPOPUP_PYTHON_SCREEN,
	BUTTONPOPUP_MOVIE,
	BUTTONPOPUP_DETAILS,
	BUTTONPOPUP_ADMIN,
	BUTTONPOPUP_ADMIN_PASSWORD,
	BUTTONPOPUP_EXTENDED_GAME,
	BUTTONPOPUP_DIPLOMACY,
	BUTTONPOPUP_ADDBUDDY,
	BUTTONPOPUP_FORCED_DISCONNECT,
	BUTTONPOPUP_PITBOSS_DISCONNECT,
	BUTTONPOPUP_KICKED,
	BUTTONPOPUP_EVENT,
	BUTTONPOPUP_FREE_COLONY,
	BUTTONPOPUP_CHOOSE_PROFESSION,
	BUTTONPOPUP_PURCHASE_EUROPE_UNIT,
	BUTTONPOPUP_FOUNDING_FATHER,
	BUTTONPOPUP_CIVIC_OPTION,
	BUTTONPOPUP_TRADE_ROUTES,
	BUTTONPOPUP_YIELD_IMPORT_EXPORT,
	BUTTONPOPUP_PROMOTE,
	BUTTONPOPUP_CHOOSE_GOODY,
	BUTTONPOPUP_SELECT_YIELD_AMOUNT,
	BUTTONPOPUP_EUROPE_UNIT,
	BUTTONPOPUP_TALK_NATIVES,
	///TKs Invention Core Mod v 1.0
	BUTTONPOPUP_CHOOSE_INVENTION,
	//TK Tax
	BUTTONPOPUP_TAX_ADVISOR,
	//TKe
	BUTTONPOPUP_RANSOM_KNIGHT,
	BUTTONPOPUP_ARMORSMITH,
	BUTTONPOPUP_MARKET,
	BUTTONPOPUP_NOBLES_JOIN,
	///Tks Return Home
	BUTTONPOPUP_RETURN_HOME,
	///Tke
	// Teacher List - start - Nightinggale
	BUTTONPOPUP_TEACHER_LIST,
	// Teacher List - end - Nightinggale
	// R&R, Robert Surcouf, Custom House Popup-Screen START
	BUTTONPOPUP_CUSTOM_HOUSE,
	BUTTONPOPUP_DOMESTIC_MARKET,
	// R&R, Robert Surcouf, Custom House Popup-Screen END

#ifdef _USRDLL
	NUM_BUTTONPOPUP_TYPES
#endif
};

enum DllExport ClimateTypes
{
	NO_CLIMATE = -1,
};

enum DllExport SeaLevelTypes
{
	NO_SEALEVEL = -1,
};

enum DllExport EuropeTypes
{
	NO_EUROPE = -1,
};

enum DllExport CustomMapOptionTypes
{
	NO_CUSTOM_MAPOPTION = -1,
};

enum DllExport WorldSizeTypes
{
	NO_WORLDSIZE = -1,

	WORLDSIZE_TINY,
	WORLDSIZE_SMALL,
	WORLDSIZE_STANDARD,
	WORLDSIZE_LARGE,
	WORLDSIZE_HUGE,

#ifdef _USRDLL
	NUM_WORLDSIZE_TYPES
#endif
};

// This is our current relationship with each
// one of our connected network peers
enum DllExport InitStates
{
	INIT_INACTIVE,
	INIT_CONNECTED,
	INIT_SENT_READY,
	INIT_READY,
	INIT_ASSIGNED_ID,
	INIT_SENT_ID,
	INIT_PEER,
	INIT_FILE_TRANSFER,
	INIT_TRANSFER_COMPLETE,
	INIT_AUTHORIZED,
	INIT_MAP_CONFIRMED,
	INIT_GAME_STARTED,
};

enum DllExport TerrainTypes
{
	NO_TERRAIN = -1,
};

enum DllExport PlotTypes
{
	NO_PLOT = -1,

	PLOT_PEAK,
	PLOT_HILLS,
	PLOT_LAND,
	PLOT_OCEAN,

#ifdef _USRDLL
	NUM_PLOT_TYPES
#endif
};

enum DllExport EmphasizeTypes
{
	NO_EMPHASIZE = -1,
};

enum DllExport GameOptionTypes
{
	NO_GAMEOPTION = -1,

	GAMEOPTION_ADVANCED_START,
	GAMEOPTION_NO_CITY_RAZING,
	GAMEOPTION_AGGRESSIVE_AI,
	// < JAnimals Mod Start >
	GAMEOPTION_NO_WILD_LAND_ANIMALS,
	GAMEOPTION_NO_WILD_SEA_ANIMALS,
	// < JAnimals Mod End >
	GAMEOPTION_LEAD_ANY_CIV,
	GAMEOPTION_PERMANENT_ALLIANCES,
	GAMEOPTION_ALWAYS_WAR,
	GAMEOPTION_ALWAYS_PEACE,
	GAMEOPTION_ONE_CITY_CHALLENGE,
	GAMEOPTION_NO_CHANGING_WAR_PEACE,
	GAMEOPTION_NEW_RANDOM_SEED,
	GAMEOPTION_LOCK_MODS,
	GAMEOPTION_NO_GOODY_HUTS,
	GAMEOPTION_NO_EVENTS,

#ifdef _USRDLL
	NUM_GAMEOPTION_TYPES
#endif
};

enum DllExport MultiplayerOptionTypes
{
	NO_MPOPTION = -1,

	MPOPTION_SIMULTANEOUS_TURNS,
	MPOPTION_TAKEOVER_AI,
	MPOPTION_SHUFFLE_TEAMS,
	MPOPTION_ANONYMOUS,
	MPOPTION_TURN_TIMER,

#ifdef _USRDLL
	NUM_MPOPTION_TYPES
#endif
};

enum DllExport SpecialOptionTypes
{
	NO_SPECIALOPTION = -1,

	SPECIALOPTION_REPORT_STATS,

#ifdef _USRDLL
	NUM_SPECIALOPTION_TYPES
#endif
};

enum DllExport PlayerOptionTypes
{
	NO_PLAYEROPTION = -1,

	PLAYEROPTION_TUTORIAL,
	PLAYEROPTION_ADVISOR_POPUPS,
	PLAYEROPTION_ADVISOR_HELP,
	PLAYEROPTION_WAIT_END_TURN,
	PLAYEROPTION_MINIMIZE_POP_UPS,
	PLAYEROPTION_SHOW_FRIENDLY_MOVES,
	PLAYEROPTION_SHOW_ENEMY_MOVES,
	PLAYEROPTION_QUICK_MOVES,
	PLAYEROPTION_QUICK_ATTACK,
	PLAYEROPTION_QUICK_DEFENSE,
	PLAYEROPTION_STACK_ATTACK,
	PLAYEROPTION_AUTO_PROMOTION,
	PLAYEROPTION_SAFE_AUTOMATION,
	PLAYEROPTION_NUMPAD_HELP,
	PLAYEROPTION_NO_UNIT_CYCLING,
	PLAYEROPTION_NO_UNIT_RECOMMENDATIONS,
	PLAYEROPTION_RIGHT_CLICK_MENU,
	PLAYEROPTION_LEAVE_FORESTS,
	PLAYEROPTION_MODDER_1,
	PLAYEROPTION_MODDER_2,
	PLAYEROPTION_MODDER_3,
	PLAYEROPTION_MODDER_4,
	PLAYEROPTION_MODDER_5,
	PLAYEROPTION_MODDER_6,

#ifdef _USRDLL
	NUM_PLAYEROPTION_TYPES
#endif
};

enum DllExport GraphicOptionTypes
{
	NO_GRAPHICOPTION = -1,

	GRAPHICOPTION_HEALTH_BARS,
	GRAPHICOPTION_NO_COMBAT_ZOOM,
	GRAPHICOPTION_NO_ENEMY_GLOW,
	GRAPHICOPTION_FROZEN_ANIMATIONS,
	GRAPHICOPTION_EFFECTS_DISABLED,
	GRAPHICOPTION_GLOBE_VIEW_BUILDINGS_DISABLED,
	GRAPHICOPTION_FULLSCREEN,
	GRAPHICOPTION_LOWRES_TEXTURES,
	GRAPHICOPTION_HIRES_TERRAIN,
	GRAPHICOPTION_NO_MOVIES,

#ifdef _USRDLL
	NUM_GRAPHICOPTION_TYPES
#endif
};

enum DllExport ForceControlTypes
{
	NO_FORCECONTROL = -1,

	FORCECONTROL_SPEED,
	FORCECONTROL_HANDICAP,
	FORCECONTROL_OPTIONS,
	FORCECONTROL_VICTORIES,
	FORCECONTROL_MAX_TURNS,
	FORCECONTROL_MAX_CITY_ELIMINATION,
	FORCECONTROL_ADVANCED_START,

#ifdef _USRDLL
	NUM_FORCECONTROL_TYPES
#endif
};

enum DllExport TileArtTypes
{
	TILE_ART_TYPE_NONE = -1,
	TILE_ART_TYPE_TREES,
	TILE_ART_TYPE_HALF_TILING,
	NUM_TILE_ART_TYPES
};

enum DllExport TerrainGroupTypes
{
	TERRAIN_GROUP_NONE = -1,
	TERRAIN_GROUP_OCEAN,
	TERRAIN_GROUP_COAST,
	TERRAIN_GROUP_LAND,
	NUM_TERRAIN_GROUP_TYPES
};

enum DllExport VictoryTypes
{
	NO_VICTORY = -1,
};

enum DllExport FeatureTypes
{
	NO_FEATURE = -1,
};

enum DllExport BonusTypes
{
	NO_BONUS = -1,
};

enum DllExport ImprovementTypes
{
	NO_IMPROVEMENT = -1,
};

enum DllExport RouteTypes
{
	NO_ROUTE = -1,
};

enum DllExport GoodyTypes
{
	NO_GOODY = -1,
};

enum DllExport BuildTypes
{
	NO_BUILD = -1,
};

enum DllExport FontSymbols
{
	// 'OTHER' symbols
	HAPPY_CHAR = 0,
	UNHAPPY_CHAR,
	HEALTHY_CHAR,
	UNHEALTHY_CHAR,
	BULLET_CHAR,
	STRENGTH_CHAR,
	MOVES_CHAR,
	RELIGION_CHAR,
	STAR_CHAR,
	SILVER_STAR_CHAR,
	TRADE_CHAR,
	DEFENSE_CHAR,
	GREAT_PEOPLE_CHAR,
	BAD_GOLD_CHAR,
	BAD_FOOD_CHAR,
	EATEN_FOOD_CHAR,
	GOLDEN_AGE_CHAR,
	ANGRY_POP_CHAR,
	OPEN_BORDERS_CHAR,
	DEFENSIVE_PACT_CHAR,
	MAP_CHAR,
	OCCUPATION_CHAR,
	REBEL_CHAR,
	GOLD_CHAR,
	POWER_CHAR,

#ifdef _USRDLL
	MAX_NUM_SYMBOLS
#endif
};

enum DllExport HandicapTypes
{
	NO_HANDICAP = -1,
};

enum DllExport GameSpeedTypes
{
	NO_GAMESPEED = -1,
};

enum DllExport TurnTimerTypes
{
	NO_TURNTIMER = -1,
};

enum DllExport EraTypes
{
	NO_ERA = -1,
};

enum DllExport CivilizationTypes
{
	NO_CIVILIZATION = -1,
};

enum DllExport LeaderHeadTypes
{
	NO_LEADER = -1,
};

// Used for managing Art Differences based on nationality
enum DllExport ArtStyleTypes
{
	NO_ARTSTYLE = -1,
};
//Androrc UnitArtStyles
enum DllExport UnitArtStyleTypes
{
	NO_UNIT_ARTSTYLE = -1,
};
//Androrc End
enum DllExport CitySizeTypes
{
	NO_CITYSIZE = -1,

	CITYSIZE_SMALL,
	CITYSIZE_MEDIUM,
	CITYSIZE_LARGE,

#ifdef _USRDLL
	NUM_CITYSIZE_TYPES
#endif
};

enum DllExport FootstepAudioTypes
{
	NO_FOOTSTEPAUDIO = -1,
};

enum DllExport FootstepAudioTags
{
	NO_FOOTSTEPAUDIO_TAG = -1,
};

enum DllExport ChatTargetTypes
{
	NO_CHATTARGET = -1,
	CHATTARGET_ALL = -2,
	CHATTARGET_TEAM = -3,
};

enum DllExport VoiceTargetTypes
{
	NO_VOICETARGET = -1,

	VOICETARGET_DIPLO,
	VOICETARGET_TEAM,
	VOICETARGET_ALL,

#ifdef _USRDLL
	NUM_VOICETARGETS
#endif
};

enum DllExport TeamTypes
{
	UNKNOWN_TEAM = -2,
	NO_TEAM = -1,
};

enum DllExport PlayerTypes
{
	UNKNOWN_PLAYER = -2,
	NO_PLAYER = -1,
};

enum DllExport TraitTypes
{
	NO_TRAIT = -1,
};

enum DllExport OrderTypes
{
	NO_ORDER = -1,

	ORDER_TRAIN,
	ORDER_CONSTRUCT,
	ORDER_CONVINCE,

#ifdef _USRDLL
	NUM_ORDER_TYPES
#endif
};

enum DllExport TaskTypes
{
	TASK_RAZE,
	TASK_GIFT,
	TASK_SET_ALL_CITIZENS_AUTOMATED,
	TASK_SET_CITIZEN_AUTOMATED,
	TASK_SET_AUTOMATED_PRODUCTION,
	TASK_SET_EMPHASIZE,
	TASK_CHANGE_WORKING_PLOT,
	TASK_CHANGE_PROFESSION,
	TASK_EJECT_TO_TRANSPORT,
	TASK_REPLACE_CITIZEN,
	TASK_CLEAR_WORKING_OVERRIDE,
	TASK_HURRY,
	TASK_CLEAR_ORDERS,
	TASK_RALLY_PLOT,
	TASK_CLEAR_RALLY_PLOT,
	TASK_LIBERATE,
	TASK_YIELD_IMPORT,
	TASK_YIELD_EXPORT,
	TASK_YIELD_LEVEL,
	TASK_CLEAR_SPECIALTY,
	TASK_EDUCATE,
	TASK_PUSH_TRAIN_UNIT,
	TASK_PUSH_CONSTRUCT_BUILDING,
	TASK_CHEAT,
	// Teacher List - start - Nightinggale
	TASK_CHANGE_ORDERED_STUDENTS,
	// Teacher List - end - Nightinggale
	// custom house - network fix - start - Nightinggale
	TASK_CHANGE_CUSTOM_HOUSE_SETTINGS,
	// custom house - network fix - end - Nightinggale
	TASK_YIELD_TRADEROUTE, // transport feeder - Nightinggale
#ifdef _USRDLL
	NUM_TASK_TYPES
#endif
};

enum DllExport PlayerActionTypes
{
	PLAYER_ACTION_BUY_EUROPE_UNIT,
	PLAYER_ACTION_SELL_YIELD_UNIT,
	PLAYER_ACTION_BUY_YIELD_UNIT,
	PLAYER_ACTION_LOAD_UNIT_FROM_EUROPE,
	PLAYER_ACTION_UNLOAD_UNIT_TO_EUROPE,
	PLAYER_ACTION_TRANSFER_UNIT_IN_EUROPE,
	PLAYER_ACTION_SET_OPTION,
	PLAYER_ACTION_AUTO_MOVES,
	PLAYER_ACTION_TURN_COMPLETE,
	PLAYER_ACTION_APPLY_EVENT,
	PLAYER_ACTION_CONVINCE_FATHER,
	PLAYER_ACTION_SET_CIVIC,
	PLAYER_ACTION_RECEIVE_GOODY,
	PLAYER_ACTION_BUY_UNITS_FROM_KING,
	PLAYER_ACTION_HURRY,
	PLAYER_ACTION_EUROPE_CHANGE_PROFESSION,
	PLAYER_ACTION_FEAT,

#ifdef _USRDLL
	NUM_PLAYER_ACTION_TYPES
#endif
};

enum DllExport BuildingClassTypes
{
	NO_BUILDINGCLASS = -1,
};

enum DllExport BuildingTypes
{
	NO_BUILDING = -1,
};

enum DllExport SpecialBuildingTypes
{
	NO_SPECIALBUILDING = -1,
};

enum DllExport AxisTypes
{
	AXIS_X,
	AXIS_Y,
	AXIS_Z,
	NUM_AXIS_TYPES
};

enum DllExport InfoBarTypes
{
	INFOBAR_STORED,
	INFOBAR_RATE,
	INFOBAR_RATE_EXTRA,
	INFOBAR_EMPTY,

#ifdef _USRDLL
	NUM_INFOBAR_TYPES
#endif
};

enum DllExport HealthBarTypes
{
	HEALTHBAR_ALIVE_ATTACK,
	HEALTHBAR_ALIVE_DEFEND,
	HEALTHBAR_DEAD,

#ifdef _USRDLL
	NUM_HEALTHBAR_TYPES
#endif
};

enum DllExport ConceptTypes
{
	NO_CONCEPT = -1,
};

enum DllExport CalendarTypes
{
	NO_CALENDAR = -1,

	CALENDAR_DEFAULT,
	CALENDAR_BI_YEARLY,
	CALENDAR_YEARS,
	CALENDAR_TURNS,
	CALENDAR_SEASONS,
	CALENDAR_MONTHS,
	CALENDAR_WEEKS,
};

enum DllExport SeasonTypes
{
	NO_SEASON = -1,
};

enum DllExport MonthTypes
{
	NO_MONTH = -1,
};

enum DllExport DenialTypes
{
	NO_DENIAL = -1,

	DENIAL_UNKNOWN,
	DENIAL_NEVER,
	DENIAL_TOO_MUCH,
	DENIAL_MYSTERY,
	DENIAL_JOKING,
	DENIAL_CONTACT_THEM,
	DENIAL_VICTORY,
	DENIAL_ATTITUDE,
	DENIAL_ATTITUDE_THEM,
	DENIAL_POWER_US,
	DENIAL_POWER_YOU,
	DENIAL_POWER_THEM,
	DENIAL_TOO_MANY_WARS,
	DENIAL_NO_GAIN,
	DENIAL_NOT_INTERESTED,
	DENIAL_NOT_ALLIED,
	DENIAL_RECENT_CANCEL,
	DENIAL_WORST_ENEMY,
	DENIAL_POWER_YOUR_ENEMIES,
	DENIAL_TOO_FAR,
	DENIAL_WAR_NOT_POSSIBLE_US,
	DENIAL_WAR_NOT_POSSIBLE_YOU,
	DENIAL_PEACE_NOT_POSSIBLE_US,
	DENIAL_PEACE_NOT_POSSIBLE_YOU,
	///TKs Med
	DENIAL_CULTURE_YOU,
	///Tke

#ifdef _USRDLL
	NUM_DENIAL_TYPES
#endif
};

enum DllExport DomainTypes
{
	NO_DOMAIN = -1,

	DOMAIN_SEA,
	DOMAIN_LAND,
	DOMAIN_IMMOBILE,
	//DOMAIN_AIR, // why was this added without any mentioning in XML ???

#ifdef _USRDLL
	NUM_DOMAIN_TYPES
#endif
};

enum DllExport UnitClassTypes
{
	NO_UNITCLASS = -1,
};

enum DllExport UnitTypes
{
	NO_UNIT = -1,
};

enum DllExport ProfessionTypes
{
	INVALID_PROFESSION = -2,
	NO_PROFESSION = -1,
};

enum DllExport SpecialUnitTypes
{
	NO_SPECIALUNIT = -1,
};

enum DllExport UnitCombatTypes
{
	NO_UNITCOMBAT = -1,
};
///TKs Med
enum DllExport UnitEquipmentTypes
{
	NO_EQUIPMENT = -1,

	EQUIPMENT_ANY,
	EQUIPMENT_HEAVY_ARMOR,
	EQUIPMENT_ANY_ARMOR,
	EQUIPMENT_ARMOR_HORSES,

#ifdef _USRDLL
	NUM_EQUIPMENT_TYPES
#endif

};

enum DllExport TradeRouteTypes
{
	NO_TRADE_ROUTES = -1,

	TRADE_ROUTE_EUROPE,
	TRADE_ROUTE_FAIR,
	TRADE_ROUTE_SPICE_ROUTE,
	TRADE_ROUTE_SILK_ROAD,

#ifdef _USRDLL
	NUM_TRADE_ROUTES_TYPES
#endif

};

enum DllExport MedCityTypes
{
	CITYTYPE_DEFAULT = -1,

	CITYTYPE_COMMERCE,
	CITYTYPE_MONASTERY,
	CITYTYPE_OUTPOST,
	CITYTYPE_BAILEY,
	CITYTYPE_CASTLE,
	CITYTYPE_MILITARY,
	CITYTYPE_NONE_MILITARY,
	CITYTYPE_NONE_MONASTERY,

#ifdef _USRDLL
	NUM_CITY_TYPES
#endif

};

enum DllExport TradeScreenTypes
{
	TRADE_SCREEN_DEFAULT = -1,

	TRADE_SCREEN_MOTHERLAND,
	TRADE_SCREEN_TRADE_FAIR,
	TRADE_SCREEN_SPICE_ROUTE,
	TRADE_SCREEN_SILK_ROAD,
	TRADE_SCREEN_EUROPE,

#ifdef _USRDLL
	NUM_TRADE_SCREEN_TYPES
#endif

};

enum DllExport ModCodeTypes
{
    VOID_CODE = -1,

	NO_MOD_CODE,
	MODER_CODE_FASTER_CHOP_TREES,
	MODER_CODE_SPICE_ROUTE,
	MODER_CODE_SILK_ROAD_ROUTE,
	MODER_CODE_TRADING_POST,
	MODER_CODE_ONLY_NONE_NATIVES,
	MODER_CODE_NATIVES_ONLY,
	MODER_CODE_ANYONE,
	MODER_CODE_NATIVES_VIKING_AGE,
	MODER_CODE_ALLOWS_TRADE_FAIR,
	MODER_CODE_CANNOT_WORK_BUILDINGS,
	MODER_CODE_NONE_MILITARY,
	MODER_CODE_SQUIRE,
	MODER_CODE_CRAFTMEN_NOBLES,
	MODER_CODE_AI_ONLY,
	MODER_CODE_CANNOT_LEARN_NATIVE,


#ifdef _USRDLL
	NUM_MOD_CODE_TYPES
#endif

};

enum DllExport CensureType
{
	NO_CENSURE = -1,

	CENSURE_EXCOMMUNICATION,
	CENSURE_INTERDICT,
	CENSURE_ANATHEMA,
	CENSURE_CRUSADE,

#ifdef _USRDLL
	NUM_CENSURE_TYPES
#endif

};
///TKe
enum DllExport UnitAITypes
{
	NO_UNITAI = -1,

	UNITAI_UNKNOWN,
	// < JAnimals Mod Start >
	UNITAI_ANIMAL,
	// < JAnimals Mod End >
	UNITAI_COLONIST,
	UNITAI_SETTLER,
	UNITAI_WORKER,
	UNITAI_MISSIONARY,
	UNITAI_SCOUT,
	UNITAI_WAGON,
	UNITAI_TREASURE,
	UNITAI_YIELD,
	UNITAI_GENERAL,
	UNITAI_DEFENSIVE,
	UNITAI_OFFENSIVE,
	UNITAI_COUNTER,
	UNITAI_TRANSPORT_SEA,
	UNITAI_ASSAULT_SEA,
	UNITAI_COMBAT_SEA,
	UNITAI_PIRATE_SEA,
	///TKs Med
	UNITAI_TRADER,
	UNITAI_HUNTSMAN,
	UNITAI_MARAUDER,
	///Tke

#ifdef _USRDLL
	NUM_UNITAI_TYPES
#endif
};

enum DllExport InvisibleTypes
{
	NO_INVISIBLE = -1,
};

enum DllExport ProbabilityTypes
{
	NO_PROBABILITY = -1,

	PROBABILITY_LOW,
	PROBABILITY_REAL,
	PROBABILITY_HIGH,

#ifdef _USRDLL
	NUM_PROBABILITY_TYPES
#endif
};

enum DllExport ActivityTypes
{
	NO_ACTIVITY = -1,

	ACTIVITY_AWAKE,
	ACTIVITY_HOLD,
	ACTIVITY_SLEEP,
	ACTIVITY_HEAL,
	ACTIVITY_SENTRY,
	ACTIVITY_MISSION,
	///TKs Med
	ACTIVITY_COLLECT_TAXES,
	ACTIVITY_HUNT,
	///Tke

#ifdef _USRDLL
	NUM_ACTIVITY_TYPES
#endif
};

enum DllExport AutomateTypes
{
	NO_AUTOMATE = -1,

	AUTOMATE_BUILD,
	AUTOMATE_CITY,
	AUTOMATE_EXPLORE,
	AUTOMATE_SAIL,
	///TKs Med
	AUTOMATE_HUNT,
	AUTOMATE_TRAVEL_FAIR,
	AUTOMATE_TRAVEL_SILK_ROAD,
	AUTOMATE_SAIL_SPICE_ROUTE,
	///TKe
	AUTOMATE_TRANSPORT_ROUTES,
	AUTOMATE_TRANSPORT_FULL,
	///Tks Return Home
	AUTOMATE_RETURN_HOME,
	AUTOMATE_IMMIGRATION,
	///TKe
	AUTOMATE_FULL,

#ifdef _USRDLL
	NUM_AUTOMATE_TYPES
#endif
};

// any additions need to be reflected in GlobalTypes.xml
enum DllExport MissionTypes
{
	NO_MISSION = -1,

	MISSION_MOVE_TO,
	MISSION_ROUTE_TO,
	MISSION_MOVE_TO_UNIT,
	MISSION_SKIP,
	MISSION_SLEEP,
	MISSION_FORTIFY,
	MISSION_HEAL,
	MISSION_SENTRY,
	MISSION_BOMBARD,
	MISSION_PILLAGE,
	MISSION_FOUND,
	MISSION_JOIN_CITY,
	MISSION_BUILD,
	MISSION_LEAD,

	MISSION_BEGIN_COMBAT,
	MISSION_END_COMBAT,
	MISSION_SURRENDER,
	MISSION_CAPTURED,
	MISSION_IDLE,
	MISSION_DIE,
	MISSION_DAMAGE,
	MISSION_MULTI_SELECT,
	MISSION_MULTI_DESELECT,
	///TKs Med
	MISSION_FOUND_MONASTERY,
	MISSION_FOUND_OUTPOST,
	MISSION_COLLECT_TAXES,
	MISSION_HUNT,
	///Tke

#ifdef _USRDLL
	NUM_MISSION_TYPES
#endif
};

enum DllExport MissionAITypes
{
	NO_MISSIONAI = -1,

	MISSIONAI_SHADOW,
	MISSIONAI_GROUP,
	MISSIONAI_LOAD_ASSAULT,
	MISSIONAI_LOAD_SETTLER,
	MISSIONAI_LOAD_SPECIAL,
	MISSIONAI_GUARD_CITY,
	MISSIONAI_GUARD_BONUS,
	MISSIONAI_GUARD_TRADE_NET,
	MISSIONAI_SPREAD,
	MISSIONAI_EXPLORE,
	MISSIONAI_PILLAGE,
	MISSIONAI_FOUND,
	MISSIONAI_BUILD,
	MISSIONAI_ASSAULT,
	MISSIONAI_PICKUP,
	MISSIONAI_AWAIT_PICKUP,
	MISSIONAI_SAIL_TO_EUROPE,
	MISSIONAI_SAIL_FROM_EUROPE,
	MISSIONAI_TRANSPORT,
	MISSIONAI_TRANSPORT_SEA,
	MISSIONAI_PIRACY,
	MISSIONAI_BOMBARD,
	MISSIONAI_LEARN,
	///TKs Med
	MISSIONAI_PILGRAM,
	MISSIONAI_HUNT,
	///Tke

#ifdef _USRDLL
	NUM_MISSIONAI_TYPES
#endif
};

// any additions need to be reflected in GlobalTypes.xml
enum DllExport CommandTypes
{
	NO_COMMAND = -1,

	COMMAND_PROMOTION,
	COMMAND_UPGRADE,
	COMMAND_AUTOMATE,
	COMMAND_WAKE,
	COMMAND_CANCEL,
	COMMAND_CANCEL_ALL,
	COMMAND_STOP_AUTOMATION,
	COMMAND_DELETE,
	COMMAND_GIFT,
	COMMAND_LOAD,
	COMMAND_LOAD_UNIT,
	COMMAND_LOAD_CARGO,
	COMMAND_LOAD_YIELD,
	COMMAND_UNLOAD,
	COMMAND_UNLOAD_ALL,
	COMMAND_LEARN,
	COMMAND_KING_TRANSPORT,
	COMMAND_ESTABLISH_MISSION,
	COMMAND_SPEAK_WITH_CHIEF,
	COMMAND_YIELD_TRADE,
	COMMAND_SAIL_TO_EUROPE,
	COMMAND_CHOOSE_TRADE_ROUTES,
	COMMAND_ASSIGN_TRADE_ROUTE,
	COMMAND_PROMOTE,
	COMMAND_PROFESSION,
	COMMAND_CLEAR_SPECIALTY,
	COMMAND_HOTKEY,
	///Tks Med
	COMMAND_CONVERT_UNIT,
	COMMAND_HOLD_FEAST,
	COMMAND_TRAVEL_TO_FAIR,
	COMMAND_SAIL_SPICE_ROUTE,
	COMMAND_TRAVEL_SILK_ROAD,
	///TKs Home City
	COMMAND_ASSIGN_HOME_CITY,
	///TKs Med Unit COmmands
	COMMAND_HIRE_GUARD,
	COMMAND_CALL_BANNERS,
	COMMAND_BUILD_HOME,
	COMMAND_BUILD_TRADINGPOST,

	///Tke
	#ifdef _USRDLL
	NUM_COMMAND_TYPES
#endif
};

enum DllExport ControlTypes
{
	NO_CONTROL = -1,

	CONTROL_CENTERONSELECTION,
	CONTROL_SELECTYUNITTYPE,
	CONTROL_SELECTYUNITALL,
	CONTROL_SELECTCITY,
	CONTROL_SELECTCAPITAL,
	CONTROL_NEXTCITY,
	CONTROL_PREVCITY,
	CONTROL_NEXTUNIT,
	CONTROL_PREVUNIT,
	CONTROL_CYCLEUNIT,
	CONTROL_CYCLEUNIT_ALT,
	CONTROL_LASTUNIT,
	CONTROL_ENDTURN,
	CONTROL_ENDTURN_ALT,
	CONTROL_FORCEENDTURN,
	CONTROL_AUTOMOVES,
	CONTROL_PING,
	CONTROL_SIGN,
	CONTROL_GRID,
	CONTROL_BARE_MAP,
	CONTROL_YIELDS,
	CONTROL_RESOURCE_ALL,
	CONTROL_UNIT_ICONS,
	CONTROL_GLOBELAYER,
	CONTROL_SCORES,
	CONTROL_LOAD_GAME,
	CONTROL_OPTIONS_SCREEN,
	CONTROL_RETIRE,
	CONTROL_SAVE_GROUP,
	CONTROL_SAVE_NORMAL,
	CONTROL_QUICK_SAVE,
	CONTROL_QUICK_LOAD,
	CONTROL_ORTHO_CAMERA,
	CONTROL_CYCLE_CAMERA_FLYING_MODES,
	CONTROL_ISOMETRIC_CAMERA_LEFT,
	CONTROL_ISOMETRIC_CAMERA_RIGHT,
	CONTROL_FLYING_CAMERA,
	CONTROL_MOUSE_FLYING_CAMERA,
	CONTROL_TOP_DOWN_CAMERA,
	CONTROL_CIVILOPEDIA,
	CONTROL_FOREIGN_SCREEN,
	CONTROL_CONGRESS_SCREEN,
	CONTROL_REVOLUTION_SCREEN,
	CONTROL_EUROPE_SCREEN,
	CONTROL_MILITARY_SCREEN,
	CONTROL_FATHER_SCREEN,
	///TKs Invention Core Mod v 1.0
	CONTROL_TECHNOLOGY_SCREEN,
	CONTROL_TRADE_SCREEN,
	CONTROL_SPICE_ROUTE_SCREEN,
	CONTROL_SILK_ROAD_SCREEN,
	CONTROL_TRADE_FAIR_SCREEN,
	CONTROL_IMMIGRATION_SCREEN,
	///TKE
	CONTROL_TURN_LOG,
	CONTROL_CHAT_ALL,
	CONTROL_CHAT_TEAM,
	CONTROL_DOMESTIC_SCREEN,
	CONTROL_VICTORY_SCREEN,
	CONTROL_INFO,
	CONTROL_GLOBE_VIEW,
	CONTROL_DETAILS,
	CONTROL_ADMIN_DETAILS,
	CONTROL_HALL_OF_FAME,
	CONTROL_WORLD_BUILDER,
	CONTROL_DIPLOMACY,
	CONTROL_SELECT_HEALTHY,
	CONTROL_FREE_COLONY,
	///TKs Cheat
	CONTROL_AI_AUTOPLAY,
	CONTROL_AI_AUTOPLAY5,
	CONTROL_AI_AUTOPLAY25,
	CONTROL_AI_AUTOPLAY100,
	CONTROL_AI_AUTOPLAY_REV,
	CONTROL_LEARN_TECH,
	CONTROL_FOR_TESTING,
	///TKe

#ifdef _USRDLL
	NUM_CONTROL_TYPES
#endif
};

enum DllExport PromotionTypes
{
	NO_PROMOTION = -1,
};

enum DllExport HurryTypes
{
	NO_HURRY = -1,
};

enum DllExport CultureLevelTypes
{
	NO_CULTURELEVEL = -1,
};

enum DllExport CivicOptionTypes
{
	NO_CIVICOPTION = -1,
	CIVICOPTION_INVENTIONS,
};

enum DllExport CivicTypes
{
	NO_CIVIC = -1,
};

enum DllExport WarPlanTypes
{
	NO_WARPLAN = -1,

	WARPLAN_ATTACKED_RECENT,
	WARPLAN_ATTACKED,
	WARPLAN_PREPARING_LIMITED,
	WARPLAN_PREPARING_TOTAL,
	WARPLAN_LIMITED,
	WARPLAN_TOTAL,
	WARPLAN_DOGPILE,
	WARPLAN_EXTORTION,

#ifdef _USRDLL
	NUM_WARPLAN_TYPES
#endif
};

enum DllExport AreaAITypes
{
	NO_AREAAI = -1,

	AREAAI_OFFENSIVE,
	AREAAI_BALANCED,
	AREAAI_DEFENSIVE,
	AREAAI_MASSING,
	AREAAI_ASSAULT,
	AREAAI_ASSAULT_MASSING,
	AREAAI_NEUTRAL,

#ifdef _USRDLL
	NUM_AREAAI_TYPES
#endif
};

enum DllExport EmotionTypes
{
	NO_EMOTION = -1,

	EMOTION_GREED,
	EMOTION_ANGER,
	EMOTION_ENVY,
	EMOTION_ANXIETY,
	EMOTION_SUBMISSION,

#ifdef _USRDLL
	NUM_EMOTION_TYPES
#endif
};

enum DllExport StrategyTypes
{
	NO_STRATEGY = -1,

	STRATEGY_SMALL_WAVES,
	STRATEGY_BUILDUP,
	STRATEGY_CONCENTRATED_ATTACK,
	STRATEGY_DISTRIBUTED_ATTACK,

	STRATEGY_DIE_FIGHTING,

	STRATEGY_FAST_BELLS,
	STRATEGY_CASH_FOCUS,
	STRATEGY_SELL_TO_NATIVES,
	STRATEGY_DENSE_CITY_SPACING,

	STRATEGY_REVOLUTION_PREPARING,
	STRATEGY_REVOLUTION_DECLARING,
	STRATEGY_REVOLUTION,
#ifdef _USRDLL
	NUM_STRATEGY_TYPES
#endif

};

enum DllExport EndTurnButtonStates
{
	END_TURN_GO,
	END_TURN_OVER_HIGHLIGHT,
	END_TURN_OVER_DARK,

#ifdef _USRDLL
	NUM_END_TURN_STATES
#endif
};

enum DllExport FogOfWarModeTypes
{
	FOGOFWARMODE_OFF,
	FOGOFWARMODE_UNEXPLORED,
	FOGOFWARMODE_NOVIS,

#ifdef _USRDLL
	NUM_FOGOFWARMODE_TYPES
#endif
};

enum DllExport FogTypes
{
	FOG_TYPE_NONE,
	FOG_TYPE_PARALLEL,
	FOG_TYPE_PROJECTED,
	NUM_FOG_TYPES
};

enum DllExport CameraOverlayTypes
{
	CAMERA_OVERLAY_DECAL,
	CAMERA_OVERLAY_ADDITIVE,
	NUM_CAMERA_OVERLAY_TYPES
};

enum FOWUpdateTypes
{
	FOW_UPDATE_REGULAR,
	FOW_UPDATE_IMMEDIATE,
	FOW_UPDATE_UNDO_IMMEDIATE,
	FOW_UPDATE_FORCE_CHANGE,
	NUM_FOW_UPDATE_TYPES
};

// AnimationTypes is depreciated, and will be eventually removed.
// BONUSANIMATION_* and IMPROVEMENTANIMATION_* are still used, and will be left.

enum DllExport AnimationTypes
{
	NONE_ANIMATION = -1,	// NO_ANIMATION is used by FirePlace

	BONUSANIMATION_UNIMPROVED = 1,
	BONUSANIMATION_NOT_WORKED,
	BONUSANIMATION_WORKED,

	IMPROVEMENTANIMATION_OFF = 2,
	IMPROVEMENTANIMATION_ON,
	IMPROVEMENTANIMATION_OFF_EXTRA,
	IMPROVEMENTANIMATION_ON_EXTRA_1,
	IMPROVEMENTANIMATION_ON_EXTRA_2,
	IMPROVEMENTANIMATION_ON_EXTRA_3,
	IMPROVEMENTANIMATION_ON_EXTRA_4,
};

enum DllExport EntityEventTypes
{
	ENTITY_EVENT_NONE = -1,			//!< Invalid event
};

enum DllExport AnimationPathTypes
{
	ANIMATIONPATH_NONE = -1,

	// Default animation paths
	ANIMATIONPATH_IDLE,
	ANIMATIONPATH_MOVE,
	ANIMATIONPATH_DAMAGE,				//!< Updates the damage state for the unit

	// Combat related animation paths
	ANIMATIONPATH_RANDOMIZE_ANIMATION_SET,
	ANIMATIONPATH_MELEE_STRIKE,
	ANIMATIONPATH_MELEE_HURT,
	ANIMATIONPATH_MELEE_DIE,
	ANIMATIONPATH_MELEE_FORTIFIED,
	ANIMATIONPATH_MELEE_DIE_FADE,		//!< Used only in combat. The colateral damage die should have a fade integrated.
	ANIMATIONPATH_MELEE_FLEE,			//!< Used only by settler children, so they don't die in combat

	// Ranged combat related animation paths
	ANIMATIONPATH_RANGED_STRIKE,
	ANIMATIONPATH_RANGED_DIE,
	ANIMATIONPATH_RANGED_FORTIFIED,
	ANIMATIONPATH_RANGED_RUNHIT,
	ANIMATIONPATH_RANGED_RUNDIE,
	ANIMATIONPATH_RANGED_DIE_FADE,		//!< Used only in combat. The colateral damage die should have a fade integrated.
	ANIMATIONPATH_LEADER_COMMAND,

	//mission related animation paths
	ANIMATIONPATH_HEAL,
	ANIMATIONPATH_SLEEP,
	ANIMATIONPATH_FORTIFY,
	ANIMATIONPATH_MELEE_FORTIFY,
	ANIMATIONPATH_PILLAGE,
	ANIMATIONPATH_SENTRY,
	ANIMATIONPATH_FOUND,
	ANIMATIONPATH_IRRIGATE,
	ANIMATIONPATH_BUILD,
	ANIMATIONPATH_MINE,
	ANIMATIONPATH_CHOP,
	ANIMATIONPATH_SHOVEL,
	ANIMATIONPATH_RAILROAD,
	ANIMATIONPATH_GREAT_EVENT,
	ANIMATIONPATH_SURRENDER,
};

//!<  Enumeration for the animation category types.
enum AnimationCategoryTypes
{
	ANIMCAT_NONE = -1,
};

//!< Animation category operators.
enum AnimationOperatorTypes
{
	ANIMOP_FIRST = 1001,
	ANIMOP_RAND_FPR = ANIMOP_FIRST,			//!< Sets the FPR to a random number [0..1].
	ANIMOP_SET_FPR,							//!< Sets the FPR to the input value
	ANIMOP_SET_BR,							//!< Sets the BR to true the input value is non-zero
	ANIMOP_ADD_FPR,							//!< Adds the input value to the FPR register (input can be negative)
	ANIMOP_TEST_GT,							//!< Sets/resets the BR if the FPR is greater than the input
	ANIMOP_TEST_LT,							//!< Sets/resets the BR if the FPR is less than the input
	ANIMOP_LOAD_CAS,						//!< Sets the FPR to the CAS/32.
	ANIMOP_SET_ANIMATION_SET,						//!< Modifies the current animation set, by setting it to ((FPR*32)%32)
	ANIMOP_SKIP_IF,							//!< Skips the given number of instructions if the BR is true
	ANIMOP_CAS_INCR,						//!< Increments the CAS (and resets to zero if it is the maximum)
	ANIMOP_IS_RANGED,						//!< Sets the BR to true if the unit is "ranged", and to false otherwise
	ANIMOP_DEACTIVATE_DAMAGE_LAYERS,					//!< Deactivates all animations that are layered
	ANIMOP_SETCAS_DAMAGE,					//!< Set the current animation set to the damage level of the unit (damage/art define max)
	ANIMOP_LAST
};

enum DllExport CursorTypes
{
	NO_CURSOR = -1,
};

enum DllExport FunctionTypes
{
	FUNC_NOINTERP = 0,	// NiAnimationKey::NOINTERP,
	FUNC_LINKEY,	//	= NiAnimationKey::LINKEY,
	FUNC_BEZKEY,	//	= NiAnimationKey::BEZKEY,
	FUNC_TCBKEY,	// = NiAnimationKey::TCBKEY,
	FUNC_EULERKEY,	// = NiAnimationKey::EULERKEY,
	FUNC_STEPKEY,	// = NiAnimationKey::STEPKEY,

#ifdef _USRDLL
	NUM_FUNC_TYPES	// = NiAnimationKey::NUMKEYTYPES
#endif
};

enum DllExport TradeableItems
{
	TRADE_ITEM_NONE = -1,

	TRADE_GOLD,
	TRADE_MAPS,
	TRADE_OPEN_BORDERS,
	TRADE_DEFENSIVE_PACT,
	TRADE_PERMANENT_ALLIANCE,
	TRADE_PEACE_TREATY,
	///TKs Invention Core Mod v 1.0
    //TRADE_RESEARCH,
    ///TKe

#ifdef _USRDLL
	NUM_BASIC_ITEMS,
	TRADE_YIELD = NUM_BASIC_ITEMS,
#else
	TRADE_YIELD,
#endif
    ///TKs Invention Core Mod v 1.0
    TRADE_IDEAS,
    TRADE_RESEARCH,
    ///TKe
	TRADE_CITIES,
	TRADE_PEACE,
	TRADE_WAR,
	TRADE_EMBARGO,

#ifdef _USRDLL
	NUM_TRADEABLE_HEADINGS,

	NUM_TRADEABLE_ITEMS = NUM_TRADEABLE_HEADINGS,
#endif
};

enum DllExport DiploEventTypes
{
	NO_DIPLOEVENT = -1,

	DIPLOEVENT_CONTACT,
	DIPLOEVENT_AI_CONTACT,
	DIPLOEVENT_FAILED_CONTACT,
	DIPLOEVENT_GIVE_HELP,
	DIPLOEVENT_REFUSED_HELP,
	DIPLOEVENT_ACCEPT_DEMAND,
	DIPLOEVENT_REJECTED_DEMAND,
	DIPLOEVENT_DEMAND_WAR,
	DIPLOEVENT_JOIN_WAR,
	DIPLOEVENT_NO_JOIN_WAR,
	DIPLOEVENT_STOP_TRADING,
	DIPLOEVENT_NO_STOP_TRADING,
	DIPLOEVENT_ASK_HELP,
	DIPLOEVENT_MADE_DEMAND,
	DIPLOEVENT_TARGET_CITY,
	DIPLOEVENT_ACCEPT_TAX_RATE,
	DIPLOEVENT_REFUSE_TAX_RATE,
	DIPLOEVENT_ACCEPT_KING_GOLD,
	DIPLOEVENT_REFUSE_KING_GOLD,
	DIPLOEVENT_LIVE_AMONG_NATIVES,
	DIPLOEVENT_TRANSPORT_TREASURE,
	DIPLOEVENT_FOUND_CITY,
	DIPLOEVENT_FOUND_CITY_CHECK_NATIVES,
	///TKs Med
	DIPLOEVENT_INSULT_FIRSTCONTACT,
	DIPLOEVENT_ACCEPT_VASSAL,
	DIPLOEVENT_DEMAND_VASSAL_LANDS,
	///Tke


#ifdef _USRDLL
	NUM_DIPLOEVENT_TYPES
#endif
};

enum DllExport DiploCommentTypes
{
	NO_DIPLOCOMMENT = -1
};

enum DllExport NetContactTypes
{
	NO_NETCONTACT = -1,
	NETCONTACT_INITIAL,
	NETCONTACT_RESPONSE,
	NETCONTACT_ESTABLISHED,
	NETCONTACT_BUSY,

#ifdef _USRDLL
	NUM_NETCONTACT_TYPES
#endif
};

enum DllExport ContactTypes
{
	CONTACT_JOIN_WAR,
	CONTACT_STOP_TRADING,
	CONTACT_GIVE_HELP,
	CONTACT_ASK_FOR_HELP,
	CONTACT_DEMAND_TRIBUTE,
	CONTACT_OPEN_BORDERS,
	CONTACT_DEFENSIVE_PACT,
	CONTACT_PERMANENT_ALLIANCE,
	CONTACT_PEACE_TREATY,
	CONTACT_TRADE_MAP,
	CONTACT_YIELD_GIFT,
	///TKs Invention Core Mod v 1.0
	CONTACT_TRADE_IDEAS,
	CONTACT_TRADE_RESEARCH,
	///TKe

#ifdef _USRDLL
	NUM_CONTACT_TYPES
#endif
};

enum DllExport MemoryTypes
{
	MEMORY_DECLARED_WAR,
	MEMORY_DECLARED_WAR_ON_FRIEND,
	MEMORY_HIRED_WAR_ALLY,
	MEMORY_RAZED_CITY,
	MEMORY_GIVE_HELP,
	MEMORY_REFUSED_HELP,
	MEMORY_ACCEPT_DEMAND,
	MEMORY_REJECTED_DEMAND,
	MEMORY_ACCEPTED_JOIN_WAR,
	MEMORY_DENIED_JOIN_WAR,
	MEMORY_ACCEPTED_STOP_TRADING,
	MEMORY_DENIED_STOP_TRADING,
	MEMORY_STOPPED_TRADING,
	MEMORY_STOPPED_TRADING_RECENT,
	MEMORY_HIRED_TRADE_EMBARGO,
	MEMORY_MADE_DEMAND,
	MEMORY_MADE_DEMAND_RECENT,
	MEMORY_CANCELLED_OPEN_BORDERS,
	MEMORY_EVENT_GOOD_TO_US,
	MEMORY_EVENT_BAD_TO_US,
	MEMORY_LIBERATED_CITIES,
	MEMORY_REFUSED_TAX,
	MEMORY_REVENGE_TAKEN,
	MEMORY_MISSIONARY_FAIL,
	///TKs Med
	MEMORY_INSULTED,
	MEMORY_MADE_VASSAL_DEMAND,
	//MEMORY_REJECTED_VASSAL_DEMAND,
	//MEMORY_ACCEPT_VASSAL_DEMAND,
	///TKe

#ifdef _USRDLL
	NUM_MEMORY_TYPES
#endif
};

enum DllExport AttitudeTypes
{
	NO_ATTITUDE = -1,

	ATTITUDE_FURIOUS,
	ATTITUDE_ANNOYED,
	ATTITUDE_CAUTIOUS,
	ATTITUDE_PLEASED,
	ATTITUDE_FRIENDLY,

#ifdef _USRDLL
	NUM_ATTITUDE_TYPES
#endif
};

//! Enumeration for playing events with CvLeaderheadWidget
enum DllExport LeaderheadAction
{
	NO_LEADERANIM = -1,		//!< If used with CvLeaderheadWidget::PerformAction, plays the idle animation

	LEADERANIM_GREETING,		//!< The leaderhead greets you
	LEADERANIM_FRIENDLY,		//!< The leaderhead is friendly to you
	LEADERANIM_PLEASED,			//!< The leaderhead is pleased
	LEADERANIM_CAUTIOUS,		//!< The leaderhead is cautious
	LEADERANIM_ANNOYED,			//!< The leaderhead is annoyed
	LEADERANIM_FURIOUS,			//!< The leaderhead is furious
	LEADERANIM_DISAGREE,		//!< The leaderhead makes a disagree gesture
	LEADERANIM_AGREE,				//!< The leaderhead makes an agree gesture
	LEADERANIM_OFFER_PINKY,
	LEADERANIM_PINKY_IDLE,
	LEADERANIM_PINKY_ACCEPT,
	LEADERANIM_PINKY_REJECT,

#ifdef _USRDLL
	NUM_LEADERANIM_TYPES			//!< The number of leaderhead event types
#endif
};

enum DllExport DiplomacyPowerTypes
{
	NO_DIPLOMACYPOWER		= -1,
	DIPLOMACYPOWER_WEAKER,
	DIPLOMACYPOWER_EQUAL,
	DIPLOMACYPOWER_STRONGER,

#ifdef _USRDLL
	NUM_DIPLOMACYPOWER_TYPES
#endif
};

enum DllExport FeatTypes
{
	FEAT_TREASURE,
	FEAT_TREASURE_IN_PORT,
	FEAT_CITY_MISSING_YIELD,
	FEAT_CITY_NO_FOOD,
	FEAT_CITY_INLAND,
	FEAT_EUROPE_SHIPS,
	FEAT_GOTO_EUROPE,
	FEAT_TALK_NATIVES,
	FEAT_CITY_SCREEN,
	FEAT_PAD,
	///TKs Med
	FEAT_PILGRAM,
	FEAT_MARAUDER,
	///TKe

#ifdef _USRDLL
	NUM_FEAT_TYPES
#endif
};

enum DllExport SaveGameTypes
{
	SAVEGAME_NONE = -1,

	SAVEGAME_AUTO,
	SAVEGAME_RECOVERY,
	SAVEGAME_QUICK,
	SAVEGAME_NORMAL,
	SAVEGAME_GROUP,
	SAVEGAME_DROP_QUIT,
	SAVEGAME_DROP_CONTINUE,
	SAVEGAME_PBEM,
	SAVEGAME_REPLAY,

#ifdef _USRDLL
	NUM_SAVEGAME_TYPES
#endif
};

enum DllExport InitializationStates
{
	INIT_OK,
	INIT_FAILED,

#ifdef _USRDLL
	NUM_INIT_STATES
#endif
};

enum DllExport GameType
{
	GAME_NONE = -1,

	GAME_SP_NEW,
	GAME_SP_SCENARIO,
	GAME_SP_LOAD,
	GAME_MP_NEW,
	GAME_MP_SCENARIO,
	GAME_MP_LOAD,
	GAME_HOTSEAT_NEW,
	GAME_HOTSEAT_SCENARIO,
	GAME_HOTSEAT_LOAD,
	GAME_PBEM_NEW,
	GAME_PBEM_SCENARIO,
	GAME_PBEM_LOAD,
	GAME_REPLAY,

#ifdef _USRDLL
	NUM_GAMETYPES
#endif
};

enum DllExport GameMode
{
	NO_GAMEMODE = -1,

	GAMEMODE_NORMAL,
	GAMEMODE_PITBOSS,

#ifdef _USRDLL
	NUM_GAMEMODES
#endif
};

enum DllExport GamePwdTypes
{
	NO_PWDTYPE = -1,

	PWD_NEWGAME,
	PWD_SCENARIO,
	PWD_JOINGAME,

#ifdef _USRDLL
	NUM_PWDTYPES
#endif
};

enum DllExport SlotClaim
{
	SLOTCLAIM_UNASSIGNED,
	SLOTCLAIM_RESERVED,
	SLOTCLAIM_ASSIGNED,

#ifdef _USRDLL
	NUM_SLOTCLAIMS
#endif
};

enum DllExport SlotStatus
{
	SS_OPEN,
	SS_COMPUTER,
	SS_CLOSED,
	SS_TAKEN,

	SS_MAX_SLOT_STATUS,
};

enum DllExport InterfaceVisibility
{
	INTERFACE_SHOW,
	INTERFACE_HIDE,
	INTERFACE_HIDE_ALL,
	INTERFACE_MINIMAP_ONLY,
	INTERFACE_ADVANCED_START,
};

enum DllExport GenericButtonSizes
{
	BUTTON_SIZE_46,
	BUTTON_SIZE_32,
	BUTTON_SIZE_24,
	BUTTON_SIZE_16,

	BUTTON_SIZE_CUSTOM,
};

enum DllExport MenuScreenType
{
	MENU_SCREEN_STANDARD,
	MENU_SCREEN_BASELOBBY,
	MENU_SCREEN_BASE_SCENARIO,
	MENU_SCREEN_JOIN,
	MENU_SCREEN_BASE_LOAD,
	MENU_SCREEN_LAUNCHING,
	MENU_SCREEN_BASE_INIT,

	MENU_SCREEN_OPENING_MENU,
	MENU_SCREEN_MOD_MENU,

	MENU_SCREEN_GS_BUDDYLIST,
	MENU_SCREEN_GS_CHATROOM,
	MENU_SCREEN_GS_CHANNEL,
	MENU_SCREEN_GS_CHOOSE_SCENARIO,
	MENU_SCREEN_GS_SCENARIO,
	MENU_SCREEN_GS_NAVBAR,
	MENU_SCREEN_GS_LOAD_STAGING,
	MENU_SCREEN_GS_MOTD,
	MENU_SCREEN_GS_LOGIN,
	MENU_SCREEN_GS_LOAD,
	MENU_SCREEN_GS_JOIN,
	MENU_SCREEN_GS_INIT,
	MENU_SCREEN_GS_CUSTOM_GAMES,

	MENU_SCREEN_LANLOBBY,
	MENU_SCREEN_MP_CHOOSE_SCENARIO,
	MENU_SCREEN_MP_SCENARIO,
	MENU_SCREEN_MP_LOAD_STAGING,
	MENU_SCREEN_MP_LOAD,
	MENU_SCREEN_MP_INIT,
	MENU_SCREEN_MP_CHOICES,
	MENU_SCREEN_MP_JOIN,

	MENU_SCREEN_SP_WORLD_SIZE,
	MENU_SCREEN_SP_SCENARIO,
	MENU_SCREEN_SP_LOAD,
	MENU_SCREEN_SP_INIT,
	MENU_SCREEN_SP_CHOICES,
	MENU_SCREEN_SP_ADVANCED_LOAD,
	MENU_SCREEN_SP_SIMPLE_CIV_PICKER,
	MENU_SCREEN_SP_REPLAY,
	MENU_SCREEN_SP_MAP_SCRIPT,
	MENU_SCREEN_SP_DIFFICULTY,
};

enum DllExport WorldBuilderPopupTypes
{
	WBPOPUP_NONE = -1,

	WBPOPUP_START = 200,
	WBPOPUP_CITY=WBPOPUP_START,		// first entry, starts at 0
	WBPOPUP_UNIT,
	WBPOPUP_PLAYER,
	WBPOPUP_PLOT,
	WBPOPUP_TERRAIN,
	WBPOPUP_FEATURE,
	WBPOPUP_IMPROVEMENT,
	WBPOPUP_GAME,

#ifdef _USRDLL
	NUM_WBPOPUP
#endif
};

enum DllExport EventType
{
	// mouseEvent
	EVT_LBUTTONDOWN = 1,
	EVT_LBUTTONDBLCLICK,
	EVT_RBUTTONDOWN,
	EVT_BACK,
	EVT_FORWARD,

	// kbdEvent
	EVT_KEYDOWN,
	EVT_KEYUP,
};

// Different types of load
enum DllExport LoadType
{
	LOAD_NORMAL,
	LOAD_INIT,
	LOAD_SETUP,
	LOAD_GAMETYPE,
	LOAD_REPLAY,
	LOAD_NORMAL_AND_GAMETYPE,
};

//	Available Fonts
enum DllExport FontTypes
{
	TITLE_FONT,
	GAME_FONT,
	SMALL_FONT,
	MENU_FONT,
	MENU_HIGHLIGHT_FONT,
};

enum DllExport PanelStyles
{
	// Built in styles
	PANEL_STYLE_STANDARD,
	PANEL_STYLE_SOLID,
	PANEL_STYLE_EMPTY,
	PANEL_STYLE_FLAT,
	PANEL_STYLE_IN,
	PANEL_STYLE_OUT,
	PANEL_STYLE_EXTERNAL,
	PANEL_STYLE_DEFAULT,

	// Civ specific styles
	PANEL_STYLE_CIVILPEDIA,
	PANEL_STYLE_STONE,
	PANEL_STYLE_UNITSTAT,
	PANEL_STYLE_BLUELARGE,
	PANEL_STYLE_BLUE50,

	PANEL_STYLE_TOPBAR,
	PANEL_STYLE_BOTTOMBAR,
	PANEL_STYLE_TECH,

	PANEL_STYLE_GAMEHUD_LEFT,
	PANEL_STYLE_GAMEHUD_RIGHT,
	PANEL_STYLE_GAMEHUD_CENTER,
	PANEL_STYLE_GAMEHUD_STATS,
	PANEL_STYLE_GAME_MAP,
	PANEL_STYLE_GAME_TOPBAR,
	PANEL_STYLE_HUD_HELP,

	PANEL_STYLE_CITY_LEFT,
	PANEL_STYLE_CITY_RIGHT,
	PANEL_STYLE_CITY_TOP,
	PANEL_STYLE_CITY_TANSHADE,
	PANEL_STYLE_CITY_INFO,
	PANEL_STYLE_CITY_TANTL,
	PANEL_STYLE_CITY_TANTR,
	PANEL_STYLE_CITY_COLUMNL,
	PANEL_STYLE_CITY_COLUMNC,
	PANEL_STYLE_CITY_COLUMNR,
	PANEL_STYLE_CITY_TITLE,

	PANEL_STYLE_DAWN,
	PANEL_STYLE_DAWNTOP,
	PANEL_STYLE_DAWNBOTTOM,

	PANEL_STYLE_MAIN,
	PANEL_STYLE_MAIN_BLACK25,
	PANEL_STYLE_MAIN_BLACK50,
	PANEL_STYLE_MAIN_WHITE,
	PANEL_STYLE_MAIN_WHITETAB,
	PANEL_STYLE_MAIN_TAN,
	PANEL_STYLE_MAIN_TAN15,
	PANEL_STYLE_MAIN_TANL,
	PANEL_STYLE_MAIN_TANR,
	PANEL_STYLE_MAIN_TANT,
	PANEL_STYLE_MAIN_TANB,
	PANEL_STYLE_MAIN_BOTTOMBAR,
	PANEL_STYLE_MAIN_SELECT,
};

enum DllExport ButtonStyles
{
	BUTTON_STYLE_STANDARD,
	BUTTON_STYLE_ETCHED,
	BUTTON_STYLE_FLAT,
	BUTTON_STYLE_IMAGE,
	BUTTON_STYLE_LABEL,
	BUTTON_STYLE_LINK,
	BUTTON_STYLE_SQUARE,
	BUTTON_STYLE_TOOL,
	BUTTON_STYLE_DEFAULT,

	// Civ specific styles
	BUTTON_STYLE_CIRCLE,
	BUTTON_STYLE_CITY_B01,
	BUTTON_STYLE_CITY_B02TL,
	BUTTON_STYLE_CITY_B02TR,
	BUTTON_STYLE_CITY_B02BL,
	BUTTON_STYLE_CITY_B02BR,
	BUTTON_STYLE_CITY_B03TL,
	BUTTON_STYLE_CITY_B03TC,
	BUTTON_STYLE_CITY_B03TR,
	BUTTON_STYLE_CITY_B03BL,
	BUTTON_STYLE_CITY_B03BC,
	BUTTON_STYLE_CITY_B03BR,
	BUTTON_STYLE_CITY_FLAT,
	BUTTON_STYLE_CITY_PLUS,
	BUTTON_STYLE_CITY_MINUS,

	BUTTON_STYLE_ARROW_LEFT,
	BUTTON_STYLE_ARROW_RIGHT,
	BUTTON_STYLE_ARROW_UP,
	BUTTON_STYLE_ARROW_DOWN
};

enum DllExport ImageShapes
{
	IMAGE_SHAPE_RECTANGLE,
	IMAGE_SHAPE_ELLIPSE,
	IMAGE_SHAPE_PARABOLA_TOP,
};

enum DllExport TableStyles
{
	TABLE_STYLE_STANDARD,
	TABLE_STYLE_EMPTY,
	TABLE_STYLE_ALTEMPTY,
	TABLE_STYLE_CITY,
	TABLE_STYLE_EMPTYSELECTINACTIVE,
	TABLE_STYLE_ALTDEFAULT,
	TABLE_STYLE_STAGINGROOM
};

enum DllExport EventContextTypes
{
	NO_EVENTCONTEXT = -1,

	EVENTCONTEXT_SELF,
	EVENTCONTEXT_ALL,
};

enum DllExport CivLoginStates
{
	NO_CIV_LOGIN = -1,

	LOGIN_CIV_OK,
	LOGIN_CIV_BAD_PWD,
	LOGIN_CIV_TAKEN,
	LOGIN_CIV_HAS_ID,
};

enum DllExport VersionTypes
{
	NO_VERSIONTYPE = -1,

	VERSIONTYPE_EXE,
	VERSIONTYPE_DLL,
	VERSIONTYPE_SHADERS,
	VERSIONTYPE_PYTHON,
	VERSIONTYPE_XML,
};

enum DllExport VoteResultTypes
{
	VOTERESULT_MAJORITY,
	VOTERESULT_UNANIMOUS,
};

enum DllExport VoteStatusTypes
{
	NO_VOTESTATUS = -1,

	VOTESTATUS_TIED = -2,
	VOTESTATUS_UNDECIDED = -3,
	VOTESTATUS_INCOMPLETE = -4
};

// Tab Group in Options Menu
enum DllExport TabGroupTypes
{
	NO_TABGROUP = -1,

	TABGROUP_GAME,
	TABGROUP_INPUT,
	TABGROUP_GRAPHICS,
	TABGROUP_AUDIO,
	TABGROUP_CLOCK,

#ifdef _USRDLL
	NUM_TABGROUPS
#endif
};

enum DllExport ReplayMessageTypes
{
	NO_REPLAY_MESSAGE = -1,

	REPLAY_MESSAGE_MAJOR_EVENT,
	REPLAY_MESSAGE_CITY_FOUNDED,
	REPLAY_MESSAGE_PLOT_OWNER_CHANGE,

#ifdef _USRDLL
	NUM_REPLAY_MESSAGE_TYPES
#endif
};

/*------------------------------------------------------------------------------------
Enum:		EAudioTag
Purpose:	To enumerate all of the tag strings loaded from the csv or xml files
------------------------------------------------------------------------------------*/
enum DllExport AudioTag
{
	AUDIOTAG_NONE = -1,
	AUDIOTAG_SOUNDID,
	AUDIOTAG_CONTEXTID,
	AUDIOTAG_SOUNDTYPE,
	AUDIOTAG_2DSCRIPT,
	AUDIOTAG_3DSCRIPT,
	AUDIOTAG_SOUNDSCAPE,
	AUDIOTAG_POSITION,
	AUDIOTAG_SCRIPTTYPE,
	AUDIOTAG_LOADTYPE,
	AUDIOTAG_COUNT,
};

enum DllExport CivilopediaPageTypes
{
	NO_CIVILOPEDIA_PAGE = -1,

	CIVILOPEDIA_PAGE_UNIT,
	CIVILOPEDIA_PAGE_PROFESSION,
	CIVILOPEDIA_PAGE_FATHER,
	CIVILOPEDIA_PAGE_BUILDING,
	CIVILOPEDIA_PAGE_TERRAIN,
	CIVILOPEDIA_PAGE_YIELDS,
	CIVILOPEDIA_PAGE_FEATURE,
	CIVILOPEDIA_PAGE_BONUS,
	CIVILOPEDIA_PAGE_IMPROVEMENT,
	CIVILOPEDIA_PAGE_PROMOTION,
	CIVILOPEDIA_PAGE_CIV,
	CIVILOPEDIA_PAGE_LEADER,
	CIVILOPEDIA_PAGE_CIVIC,
	CIVILOPEDIA_PAGE_CONCEPT,
	CIVILOPEDIA_PAGE_HINTS,
	///TKs Invention Core Mod v 1.0
	CIVILOPEDIA_PAGE_TECHNOLOGY,
	///TKe


#ifdef _USRDLL
	NUM_CIVILOPEDIA_PAGE_TYPES
#endif
};

enum DllExport ActionSubTypes
{
	NO_ACTIONSUBTYPE = -1,

	ACTIONSUBTYPE_INTERFACEMODE,
	ACTIONSUBTYPE_COMMAND,
	ACTIONSUBTYPE_BUILD,
	ACTIONSUBTYPE_PROMOTION,
	ACTIONSUBTYPE_UNIT,
	ACTIONSUBTYPE_CONTROL,
	ACTIONSUBTYPE_AUTOMATE,
	ACTIONSUBTYPE_MISSION,

#ifdef _USRDLL
	NUM_ACTIONSUBTYPES
#endif
};

enum DllExport GameMessageTypes
{
	GAMEMESSAGE_NETWORK_READY,
	GAMEMESSAGE_SAVE_GAME_FLAG,
	GAMEMESSAGE_SAVE_FLAG_ACK,
	GAMEMESSAGE_VERIFY_VERSION,
	GAMEMESSAGE_VERSION_NACK,
	GAMEMESSAGE_VERSION_WARNING,
	GAMEMESSAGE_GAME_TYPE,
	GAMEMESSAGE_ID_ASSIGNMENT,
	GAMEMESSAGE_FILE_INFO,
	GAMEMESSAGE_PICK_YOUR_CIV,
	GAMEMESSAGE_CIV_CHOICE,
	GAMEMESSAGE_CONFIRM_CIV_CLAIM,
	GAMEMESSAGE_CLAIM_INFO,
	GAMEMESSAGE_CIV_CHOICE_ACK,
	GAMEMESSAGE_CIV_CHOICE_NACK,
	GAMEMESSAGE_CIV_CHOSEN,
	GAMEMESSAGE_INTERIM_NOTICE,
	GAMEMESSAGE_INIT_INFO,
	GAMEMESSAGE_MAPSCRIPT_CHECK,
	GAMEMESSAGE_MAPSCRIPT_ACK,
	GAMEMESSAGE_LOAD_GAME,
	GAMEMESSAGE_PLAYER_ID,
	GAMEMESSAGE_SLOT_REASSIGNMENT,
	GAMEMESSAGE_PLAYER_INFO,
	GAMEMESSAGE_GAME_INFO,
	GAMEMESSAGE_REASSIGN_PLAYER,
	GAMEMESSAGE_PITBOSS_INFO,
	GAMEMESSAGE_LAUNCHING_INFO,
	GAMEMESSAGE_INIT_GAME,
	GAMEMESSAGE_INIT_PLAYERS,
	GAMEMESSAGE_AUTH_REQUEST,
	GAMEMESSAGE_AUTH_RESPONSE,
	GAMEMESSAGE_SYNCH_START,
	GAMEMESSAGE_EXTENDED_GAME,
	GAMEMESSAGE_JOIN_GROUP,
	GAMEMESSAGE_PUSH_MISSION,
	GAMEMESSAGE_AUTO_MISSION,
	GAMEMESSAGE_DO_COMMAND,
	GAMEMESSAGE_PUSH_ORDER,
	GAMEMESSAGE_POP_ORDER,
	GAMEMESSAGE_DO_TASK,
	GAMEMESSAGE_CHAT,
	GAMEMESSAGE_PING,
	GAMEMESSAGE_SIGN,
	GAMEMESSAGE_LINE_ENTITY,
	GAMEMESSAGE_SIGN_DELETE,
	GAMEMESSAGE_LINE_ENTITY_DELETE,
	GAMEMESSAGE_LINE_GROUP_DELETE,
	GAMEMESSAGE_PAUSE,
	GAMEMESSAGE_MP_KICK,
	GAMEMESSAGE_MP_RETIRE,
	GAMEMESSAGE_CLOSE_CONNECTION,
	GAMEMESSAGE_NEVER_JOINED,
	GAMEMESSAGE_MP_DROP_INIT,
	GAMEMESSAGE_MP_DROP_VOTE,
	GAMEMESSAGE_MP_DROP_UPDATE,
	GAMEMESSAGE_MP_DROP_RESULT,
	GAMEMESSAGE_MP_DROP_SAVE,
	GAMEMESSAGE_TOGGLE_TRADE,
	GAMEMESSAGE_IMPLEMENT_OFFER,
	GAMEMESSAGE_CHANGE_WAR,
	GAMEMESSAGE_APPLY_EVENT,
	GAMEMESSAGE_CONTACT_CIV,
	GAMEMESSAGE_DIPLO_CHAT,
	GAMEMESSAGE_SEND_OFFER,
	GAMEMESSAGE_DIPLO_EVENT,
	GAMEMESSAGE_RENEGOTIATE,
	GAMEMESSAGE_RENEGOTIATE_ITEM,
	GAMEMESSAGE_EXIT_TRADE,
	GAMEMESSAGE_KILL_DEAL,
	GAMEMESSAGE_SAVE_GAME,
	GAMEMESSAGE_UPDATE_CIVICS,
	GAMEMESSAGE_CLEAR_TABLE,
	GAMEMESSAGE_POPUP_PROCESSED,
	GAMEMESSAGE_DIPLOMACY_PROCESSED,
	GAMEMESSAGE_HOT_JOIN_NOTICE,
	GAMEMESSAGE_HOT_DROP_NOTICE,
	GAMEMESSAGE_DIPLOMACY,
	GAMEMESSAGE_POPUP,
	GAMEMESSAGE_ADVANCED_START_ACTION,
	GAMEMESSAGE_PLAYER_ACTION,
	GAMEMESSAGE_MOD_NET_MESSAGE
};

enum DllExport PopupControlLayout
{
	POPUP_LAYOUT_LEFT,
	POPUP_LAYOUT_CENTER,
	POPUP_LAYOUT_RIGHT,
	POPUP_LAYOUT_STRETCH,
	POPUP_LAYOUT_TOP,

	POPUP_LAYOUT_NUMLAYOUTS
};

enum DllExport JustificationTypes
{
	DLL_FONT_LEFT_JUSTIFY = 1<<0,
	DLL_FONT_RIGHT_JUSTIFY = 1<<1,
	DLL_FONT_CENTER_JUSTIFY = 1<<2,
	DLL_FONT_CENTER_VERTICALLY = 1<<3,
	DLL_FONT_ADDITIVE = 1<<4,
};

enum DllExport ToolTipAlignTypes
{
	TOOLTIP_TOP_LEFT,
	TOOLTIP_TOP_INLEFT,
	TOOLTIP_TOP_CENTER,
	TOOLTIP_TOP_INRIGHT,
	TOOLTIP_TOP_RIGHT,

	TOOLTIP_INTOP_RIGHT,
	TOOLTIP_CENTER_RIGHT,
	TOOLTIP_INBOTTOM_RIGHT,

	TOOLTIP_BOTTOM_RIGHT,
	TOOLTIP_BOTTOM_INRIGHT,
	TOOLTIP_BOTTOM_CENTER,
	TOOLTIP_BOTTOM_INLEFT,
	TOOLTIP_BOTTOM_LEFT,

	TOOLTIP_INBOTTOM_LEFT,
	TOOLTIP_CENTER_LEFT,
	TOOLTIP_INTOP_LEFT,
};

enum DllExport ActivationTypes
{
	ACTIVATE_NORMAL,
	ACTIVATE_CHILDFOCUS,
	ACTIVATE_MIMICPARENT,
	ACTIVATE_MIMICPARENTFOCUS,
};

enum DllExport HitTestTypes
{
	HITTEST_DEFAULT,
	HITTEST_ON,
	HITTEST_SOLID,
	HITTEST_CHILDREN,
	HITTEST_NOHIT,
};

enum DllExport GraphicLevelTypes
{
	GRAPHICLEVEL_HIGH,
	GRAPHICLEVEL_MEDIUM,
	GRAPHICLEVEL_LOW,
	GRAPHICLEVEL_CURRENT,
	GRAPHICLEVEL_BELOW_SPEC,

#ifdef _USRDLL
	NUM_GRAPHICLEVELS
#endif
};

enum DllExport EventTypes
{
	NO_EVENT = -1,
};

enum DllExport EventTriggerTypes
{
	NO_EVENTTRIGGER = -1,
};

enum DllExport AdvancedStartActionTypes
{
	NO_ADVANCEDSTARTACTION = -1,

	ADVANCEDSTARTACTION_EXIT,
	ADVANCEDSTARTACTION_UNIT,
	ADVANCEDSTARTACTION_CITY,
	ADVANCEDSTARTACTION_POP,
	ADVANCEDSTARTACTION_CULTURE,
	ADVANCEDSTARTACTION_BUILDING,
	ADVANCEDSTARTACTION_IMPROVEMENT,
	ADVANCEDSTARTACTION_ROUTE,
	ADVANCEDSTARTACTION_VISIBILITY,
	ADVANCEDSTARTACTION_AUTOMATE,

#ifdef _USRDLL
	NUM_ADVANCEDSTARTACTIONS
#endif
};

enum DllExport UnitTravelStates
{
	NO_UNIT_TRAVEL_STATE = -1,

	UNIT_TRAVEL_STATE_TO_EUROPE,
	UNIT_TRAVEL_STATE_IN_EUROPE,
	UNIT_TRAVEL_STATE_FROM_EUROPE,

	UNIT_TRAVEL_STATE_LIVE_AMONG_NATIVES,
	///TKs Med
	UNIT_TRAVEL_STATE_HIDE_UNIT,
	UNIT_TRAVEL_LOST_AT_SEA,

	UNIT_TRAVEL_STATE_TO_SPICE_ROUTE,
	UNIT_TRAVEL_STATE_IN_SPICE_ROUTE,
	UNIT_TRAVEL_STATE_FROM_SPICE_ROUTE,

	UNIT_TRAVEL_STATE_TO_SILK_ROAD,
	UNIT_TRAVEL_STATE_IN_SILK_ROAD,
	UNIT_TRAVEL_STATE_FROM_SILK_ROAD,

	UNIT_TRAVEL_STATE_TO_TRADE_FAIR,
	UNIT_TRAVEL_STATE_IN_TRADE_FAIR,
	UNIT_TRAVEL_STATE_FROM_TRADE_FAIR,

	UNIT_TRAVEL_STATE_FROM_IMMIGRATION,
	///TKe

#ifdef _USRDLL
	NUM_UNIT_TRAVEL_STATES
#endif
};

enum DllExport UnitAIStates
{
	NO_UNITAI_STATE = -1,

	UNITAI_STATE_DEFAULT,
	UNITAI_STATE_BEARING_GIFTS,
	UNITAI_STATE_RETURN_HOME,
	UNITAI_STATE_WANDER,

	///TKs Med
	UNITAI_STATE_MARAUDER_WANDER,
	///Tke

	UNITAI_STATE_GUARDING,
	UNITAI_STATE_ADVANCING,
	UNITAI_STATE_GROUPING,
	UNITAI_STATE_CHARGING,
	UNITAI_STATE_RETREATING,

	UNITAI_STATE_PICKUP,

	UNITAI_STATE_PURCHASED,
	UNITAI_STATE_SELL_TO_NATIVES,
	UNITAI_STATE_SAIL,

	NUM_UNITAI_STATES,
};

enum DllExport FatherCategoryTypes
{
	NO_FATHERCATEGORY = -1,
};

enum DllExport FatherTypes
{
	NO_FATHER = -1,
};

enum DllExport FatherPointTypes
{
	NO_FATHER_POINT_TYPE = -1,

};

enum DllExport AlarmTypes
{
	NO_ALARM = -1,
};

/// XML load - start - Nightinggale
enum XMLFileNames
{
	XML_FILE_CIV4ArtDefines_Bonus,
	XML_FILE_CIV4ArtDefines_Building,
	XML_FILE_CIV4ArtDefines_Civilization,
	XML_FILE_CIV4ArtDefines_Feature,
	XML_FILE_CIV4ArtDefines_Improvement,
	XML_FILE_CIV4ArtDefines_Interface,
	XML_FILE_CIV4ArtDefines_Leaderhead,
	XML_FILE_CIV4ArtDefines_Misc,
	XML_FILE_CIV4ArtDefines_Movie,
	XML_FILE_CIV4ArtDefines_Terrain,
	XML_FILE_CIV4ArtDefines_Unit,
	XML_FILE_CIV4AlarmInfos,
	XML_FILE_CIV4AnimationInfos,
	XML_FILE_CIV4AnimationPathInfos,
	XML_FILE_CIV4AttachableInfos,
	XML_FILE_CIV4AttitudeInfos,
	XML_FILE_CIV4AutomateInfos,
	XML_FILE_CIV4BonusInfos,
	XML_FILE_CIV4BuildInfos,
	XML_FILE_CIV4BuildingClassInfos,
	XML_FILE_CIV4BuildingInfos,
	XML_FILE_CIV4CalendarInfos,
	XML_FILE_CIV4CameraOverlayInfos,
	XML_FILE_CIV4CivicInfos,
	XML_FILE_CIV4CivicOptionInfos,
	XML_FILE_CIV4CivilizationInfos,
	XML_FILE_CIV4ClimateInfo,
	XML_FILE_CIV4ColorVals,
	XML_FILE_CIV4CommandInfos,
	XML_FILE_CIV4BasicInfos,
	XML_FILE_CIV4ControlInfos,
	XML_FILE_CIV4CultureLevelInfo,
	XML_FILE_CIV4CursorInfo,
	XML_FILE_CIV4DenialInfos,
	XML_FILE_CIV4DiplomacyInfos,
	XML_FILE_CIV4DomainInfos,
	XML_FILE_CIV4EffectInfos,
	XML_FILE_CIV4EmphasizeInfo,
	XML_FILE_CIV4EntityEventInfos,
	XML_FILE_CIV4EraInfos,
	XML_FILE_CIV4EuropeInfo,
	XML_FILE_CIV4EventInfos,
	XML_FILE_CIV4EventTriggerInfos,
	XML_FILE_CIV4FatherCategoryInfos,
	XML_FILE_CIV4FatherInfos,
	XML_FILE_CIV4FatherPointInfos,
	XML_FILE_Civ4FeatureInfos,
	XML_FILE_CIV4ForceControlInfos,
	XML_FILE_CIV4GameOptionInfos,
	XML_FILE_CIV4GameSpeedInfo,
	XML_FILE_CIV4GoodyInfo,
	XML_FILE_CIV4GraphicOptionInfos,
	XML_FILE_CIV4HandicapInfo,
	XML_FILE_CIV4Hints,
	XML_FILE_CIV4HurryInfo,
	XML_FILE_CIV4ImprovementInfos,
	XML_FILE_CIV4InterfaceModeInfos,
	XML_FILE_CIV4InvisibleInfos,
	XML_FILE_CIV4TerrainSettings,
	XML_FILE_CIV4LeaderHeadInfos,
	XML_FILE_CIV4MPOptionInfos,
	XML_FILE_CIV4MainMenus,
	XML_FILE_CIV4MemoryInfos,
	XML_FILE_CIV4MissionInfos,
	XML_FILE_CIV4MonthInfos,
	XML_FILE_CIV4PlayerColorInfos,
	XML_FILE_CIV4PlayerOptionInfos,
	XML_FILE_CIV4ProfessionInfos,
	XML_FILE_CIV4PromotionInfos,
	XML_FILE_CIV4RiverModelInfos,
	XML_FILE_Civ4RouteInfos,
	XML_FILE_Civ4RouteModelInfos,
	XML_FILE_CIV4SeaLevelInfo,
	XML_FILE_CIV4SeasonInfos,
	XML_FILE_CIV4SlideShowInfos,
	XML_FILE_CIV4SlideShowRandomInfos,
	XML_FILE_CIV4SpecialBuildingInfos,
	XML_FILE_CIV4SpecialUnitInfos,
	XML_FILE_CIV4TerrainInfos,
	XML_FILE_CIV4TerrainPlaneInfos,
	XML_FILE_CIV4TraitInfos,
	XML_FILE_CIV4TurnTimerInfo,
	XML_FILE_CIV4UnitAIInfos,
	XML_FILE_CIV4UnitArtStyleTypeInfos,
	XML_FILE_CIV4UnitClassInfos,
	XML_FILE_CIV4UnitCombatInfos,
	XML_FILE_CIV4FormationInfos,
	XML_FILE_CIV4UnitInfos,
	XML_FILE_CIV4VictoryInfo,
	XML_FILE_CIV4WaterPlaneInfos,
	XML_FILE_CIV4WorldInfo,
	XML_FILE_CIV4WorldPickerInfos,
	XML_FILE_CIV4YieldInfos,
};
/// XML load - end - Nightinggale

// cache XML - start - Nightinggale
enum DllExport XMLconstantTypes
{
	NO_XML_TYPE = -1,

	// The following are read uncached before the cache is set
	// MAX_NUM_LANGUAGES
	// STANDARD_CLIMATE
	// STANDARD_SEALEVEL
	// STANDARD_ERA
	// STANDARD_GAMESPEED
	// STANDARD_TURNTIMER
	// STANDARD_CALENDAR
	// STANDARD_HANDICAP

	// ***
	// *** CIV4UnitCombatInfos.xml
	// ***

	XML_UNITARMOR_PLATE,
	XML_UNITARMOR_SHIELD,
	XML_UNITTACTIC_PARRY,
	XML_UNITWEAPON_BLUNT,

	// ***
	// *** CIV4EuropeInfo.xml
	// ***

	XML_EUROPE_EAST,

	// ***
	// *** GlobalDefinesAlt.xml
	// ***

	XML_AI_ADVANCED_TECH_START,
	XML_AI_CHEAT_AUTO_BUY,
	XML_AI_CHEAT_NEEDED_DEFENDERS,
	XML_AI_CHEAT_SPICE,
	XML_AI_CHEAT_SPICE_BUY,
	XML_AI_CHEAT_SPICE_MULTIPLE,
	XML_AI_FAVORED_TERRAIN_MOD,
	XML_AI_HANDICAP_CASTLE,
	XML_AI_HANDICAP_MOTTE,
	XML_AI_MILITARY_PROFESSION_HACK,
	XML_AI_WAREHOUSE_MOD,
	XML_ALLIANCE_CULTURE_PERCENT_DENIAL,
	XML_ALLIANCE_PACT_PEACE_DENIAL,
	XML_ANIMAL_BANDITS_GUARD_GOODY_TIMER,
	XML_AUTORESEARCH_ALL,
	XML_BANQUET_YIELD_AMOUNT,
	XML_BARBARIAN_CIVILIZATION,
	XML_BARBARIAN_LEADER,
	XML_BASE_CITY_GROWTH_THRESHOLD,
	XML_BASE_CITY_LUXURY_FOOD_THRESHOLD_MOD,
	XML_BUILDINGCLASS_TRAVEL_TO_FAIR,
	XML_CALENDER_YEAR_FIRST_CHANGE_TURN,
	XML_CALENDER_YEAR_FIRST_MULTIPLIER,
	XML_CALENDER_YEAR_SECOND_CHANGE_TURN,
	XML_CALENDER_YEAR_SECOND_MULTIPLIER,
	XML_CALENDER_YEAR_THIRD_MULTIPLIER,
	XML_CAPTURED_CARGO_RANDOM_AMOUNT,
	XML_CAPTURED_LUXURY_FOOD_RANDOM_AMOUNT,
	XML_CASTLES_TO_VILLAGES_RATIO,
	XML_CHANCE_TO_CAPTURE_CRIMINALS,
	XML_CHEAT_TRAVEL_ALL,
	XML_CITY_PILGRAM_RANDOM,
	XML_COLONIAL_FORCED_PEACE_TURNS,
	XML_CONTACT_YIELD_GIFT_ENCOMEIDA_TIMER,
	XML_CONTACT_YIELD_GIFT_TECH,
	XML_DEAL_TRADE_RELATIONS_POINTS,
	XML_DEFAULT_CENSURETYPE_ANATHEMA,
	XML_DEFAULT_CENSURETYPE_ANATHEMA_COUNT,
	XML_DEFAULT_CENSURETYPE_EXCOMMUNICATION,
	XML_DEFAULT_CENSURETYPE_EXCOMMUNICATION_COUNT,
	XML_DEFAULT_CENSURETYPE_INTERDICT,
	XML_DEFAULT_CENSURETYPE_INTERDICT_COUNT,
	XML_DEFAULT_COMBAT_FOR_TRAINING,
	XML_DEFAULT_DAWN_POPULATION_UNIT,
	XML_DEFAULT_FUEDALISM_TECH,
	XML_DEFAULT_GRAIN_GROWTH_UNIT_CLASS,
	XML_DEFAULT_HUNTSMAN_PROFESSION,
	XML_DEFAULT_INVENTOR_CLASS,
	XML_DEFAULT_KNIGHT_PROFESSION_PROMOTION,
	XML_DEFAULT_KNIGHT_PROMOTION,
	XML_DEFAULT_MARAUDER_CLASS,
	XML_DEFAULT_MARUADER_SEA_PROFESSION,
	XML_DEFAULT_NATIVE_TRADE_PROFESSION,
	XML_DEFAULT_NOBLEMAN_CLASS,
	XML_DEFAULT_NOBLE_GROWTH_UNIT_CLASS,
	XML_DEFAULT_PILGRAM_CLASS,
	XML_DEFAULT_SHRINE_CLASS,
	XML_DEFAULT_SLAVE_CLASS,
	XML_DEFAULT_SPECIALBUILDING_COURTHOUSE,
	XML_DEFAULT_TEST_DEFINE,
	XML_DEFAULT_TRAINED_PROMOTION,
	XML_DEFAULT_TREASURE_YIELD,
	XML_DEFAULT_UNTRAINED_PROMOTION,
	XML_DEFAULT_VIKING_ERA,
	XML_DIPLAY_NEW_VIDEOS,
	XML_DOCKS_NEXT_UNITS,
	XML_EDUCATION_THRESHOLD,
	XML_EDUCATION_THRESHOLD_INCREASE,
	XML_ENABLE_MAP_TRADING,
	XML_ESTABLISH_TRADEPOST_COST,
	XML_FATHER_POINT_REAL_TRADE,
	XML_FOOD_CONSUMPTION_PER_POPULATION,
	XML_FOUND_MONASTERY_NUMBER,
	XML_FOUND_MOTTE_AND_BAILEY_NUMBER,
	XML_FOUND_OUTPOST_NUMBER,
	XML_FOUND_VILLAGE_NUMBER,
	XML_FREE_PEASANT_CIVIC,
	XML_HIRE_GUARD_COST,
	XML_HIRE_GUARD_PROMOTION,
	XML_IMMIGRATION_MAX_CITY_DISTANCE,
	XML_IMMIGRATION_THRESHOLD,
	XML_IMMIGRATION_THRESHOLD_INCREASE,
	XML_IMMIGRATION_TRAVEL_MOD,
	XML_INDUSTRIAL_VICTORY_SINGLE_YIELD,
	XML_JUNGLE_FEATURE,
	XML_KNIGHT_RANSOM_MOD,
	XML_MARAUDERS_DAYSOUT_RANDOM,
	XML_MARAUDERS_TOWER_RANGE,
	XML_MARAUDER_CRUMBS_EVENT,
	XML_MARAUDER_EVENT_DEFAULT_TURNS,
	XML_MAX_CITY_POPULATION_COMMUNE,
	XML_MAX_CITY_POPULATION_VILLAGE,
	XML_MAX_INSULT_MODIFIER,
	XML_MAX_LEVEL_FROM_ANIMAL_XP,
	XML_MAX_MARAUDERS,
	XML_MAX_TRAINED_EXPERIENCE,
	XML_MEDIEVAL_CENSURE,
	XML_MEDIEVAL_TRADE_TECH,
	XML_MONASTERIES_TO_VILLAGES_RATIO,
	XML_NATIVE_AUTO_SELL_PERCENT,
	XML_NATIVE_HORSES_FOR_SALE,
	XML_NATIVE_HORSES_FOR_SALE_PERCENT,
	XML_NATIVE_TECH,
	XML_NATIVE_TRADING_TRADEPOST,
	XML_NOBLE_FIELD_LABOR_PENALTY,
	XML_NO_CITY_SHORTAGE_MESSAGES,
	XML_NO_MARKED_SALES_CAP,
	XML_NO_STARTING_PLOTS_IN_JUNGLE,
	XML_PERCENT_TAX_ON_AUTOSELL_GOODS,
	XML_PILGRAM_OFFER_GOLD,
	XML_PILGRAM_OFFER_GOLD_DISTANCE_MOD,
	XML_PROFESSION_INVENTOR,
	XML_PROLIFIC_INVENTOR_THRESHOLD_INCREASE,
	XML_PROMOTION_BUILD_HOME,
	XML_RANDOM_TURNS_LOST_AT_SEA,
	XML_SLAVE_FOOD_CONSUMPTION_PER_POPULATION,
	XML_START_YEAR,
	XML_TK_AI_RESEARCH_COST_MOD_PERCENT,
	XML_TK_HUMAN_RESEARCH_COST_MOD_PERCENT,
	XML_TK_IDEAS_CITY_VALUE,
	XML_TK_PROLIFIC_INVENTOR_PROGRESS,
	XML_TK_PROLIFIC_INVENTOR_THRESHOLD,
	XML_TK_RESEARCH_PACT_IDEAS_THRESHOLD,
	XML_TK_RESEARCH_TRADE_VALUE,
	XML_TRADE_POINTS_FOR_ROUTE,
	XML_TRADE_ROUTE_SPICE,
	XML_TRADE_STIMULATES_RESEARCH_MIN_VALUE,
	XML_TRADE_STIMULATES_RESEARCH_PERCENT,
	XML_TRADING_POINTS_MOD_PERCENT,
	XML_TREASURE_UNITS_ONLY_SELECT_COASTAL,
	XML_TURNS_TO_TRAIN,
	XML_UNITCOMBAT_USE_ALL_BONUS, // 0 = use best, 1 = use all bonuses against all the enemy's types
	XML_USE_MEDIEVAL_CALENDER,
	XML_VASSAL_CIVILIZATION,
	XML_VASSAL_LEADER,
	XML_WEEKS_PER_MONTHS,
	XML_WILD_ANIMAL_LAND_BONUS_NATIVE_WEIGHT,
	XML_WILD_ANIMAL_LAND_FEATURE_NATIVE_WEIGHT,
	XML_WILD_ANIMAL_LAND_TERRAIN_NATIVE_WEIGHT,
	XML_WILD_ANIMAL_LAND_UNIT_VARIATION_WEIGHT,
	XML_WILD_ANIMAL_SEA_BONUS_NATIVE_WEIGHT,
	XML_WILD_ANIMAL_SEA_FEATURE_NATIVE_WEIGHT,
	XML_WILD_ANIMAL_SEA_TERRAIN_NATIVE_WEIGHT,
	XML_WILD_ANIMAL_SEA_UNIT_VARIATION_WEIGHT,

	// ***
	// *** vanilla GlobalDefines.xml
	// ***
	XML_ADVANCED_START_ALLOW_UNITS_OUTSIDE_CITIES,
	XML_ADVANCED_START_CITY_COST,
	XML_ADVANCED_START_CITY_COST_INCREASE,
	XML_ADVANCED_START_CITY_PLACEMENT_MAX_RANGE,
	XML_ADVANCED_START_CULTURE_COST,
	XML_ADVANCED_START_MAX_UNITS_PER_CITY,
	XML_ADVANCED_START_POPULATION_COST,
	XML_ADVANCED_START_POPULATION_COST_INCREASE,
	XML_ADVANCED_START_SIGHT_RANGE,
	XML_ADVANCED_START_VISIBILITY_COST,
	XML_ADVANCED_START_VISIBILITY_COST_INCREASE,
	XML_AI_CAN_DISBAND_UNITS,
	XML_AMPHIB_ATTACK_MODIFIER,
	XML_BASE_OCCUPATION_TURNS,
	XML_BASE_UNIT_UPGRADE_COST,
	XML_BUILDING_PRODUCTION_DECAY_PERCENT,
	XML_BUILDING_PRODUCTION_DECAY_TIME,
	XML_BUILDING_PRODUCTION_PERCENT,
	XML_BUY_PLOT_BASE_CULTURE_COST,
	XML_BUY_PLOT_CULTURE_RANGE,
	XML_BUY_PLOT_MIN_CULTURE,
	XML_BUY_PLOT_OWNED_COST_MODIFIER,
	XML_BUY_PLOT_SELLER_INCOME_PERCENT,
	XML_CAPITAL_BUILDINGCLASS,
	XML_CITY_DEFENSE_DAMAGE_HEAL_RATE,
	XML_CITY_FREE_CULTURE_GROWTH_FACTOR,
	XML_CITY_GROWTH_MULTIPLIER,
	XML_CITY_HEAL_RATE,
	XML_CITY_SCREEN_FOG_ENABLED,
	XML_CITY_YIELD_CAPACITY,
	XML_CITY_YIELD_DECAY_PERCENT,
	XML_COMBAT_DAMAGE,
	XML_COMBAT_DIE_SIDES,
	XML_COMBAT_EXPERIENCE_IN_BORDERS_PERCENT,
	XML_CONSUME_EQUIPMENT_ON_FOUND,
	XML_DEEP_WATER_TERRAIN,
	XML_DEFAULT_POPULATION_UNIT,
	XML_DIFFERENT_TEAM_FEATURE_PRODUCTION_PERCENT,
	XML_DIPLOMACY_VALUE_REMAINDER,
	XML_EDUCATION_BASE_TUITION,
	XML_ENABLE_ALLIANCE_TRADING,
	XML_ENABLE_DEFENSIVE_PACT_TRADING,
	XML_ENABLE_GOLD_TRADING,
	XML_ENABLE_OPEN_BORDERS,
	XML_END_GAME_DISPLAY_WARNING,
	XML_ENEMY_HEAL_RATE,
	XML_EUROPE_MARKET_CORRELATION_PERCENT,
	XML_EVENT_PROBABILITY_ROLL_SIDES,
	XML_EXPERIENCE_FROM_WITHDRAWL,
	XML_EXTRA_YIELD,
	XML_FATHER_COST_EXTRA_TEAM_MEMBER_MODIFIER,
	XML_FEATURE_GROWTH_MODIFIER,
	XML_FEATURE_PRODUCTION_YIELD_MAX_DISTANCE,
	XML_FIRST_EVENT_DELAY_TURNS,
	XML_FORTIFY_MODIFIER_PER_TURN,
	XML_FREE_CITY_ADJACENT_CULTURE,
	XML_FREE_CITY_CULTURE,
	XML_FRIENDLY_HEAL_RATE,
	XML_GREAT_GENERALS_THRESHOLD,
	XML_GREAT_GENERALS_THRESHOLD_INCREASE,
	XML_GREAT_GENERALS_THRESHOLD_INCREASE_TEAM,
	XML_HILLS_EXTRA_DEFENSE,
	XML_HILLS_EXTRA_MOVEMENT,
	XML_HILLS_SEE_FROM_CHANGE,
	XML_HILLS_SEE_THROUGH_CHANGE,
	XML_INITIAL_AI_CITY_PRODUCTION,
	XML_INITIAL_CITY_POPULATION,
	XML_INITIAL_CITY_ROUTE_TYPE,
	XML_KING_BUY_UNIT_PRICE_MODIFIER,
	XML_KING_INITIAL_UNIT_INCREASE,
	XML_KING_TRANSPORT_TREASURE_COMISSION,
	XML_LAKE_MAX_AREA_SIZE,
	XML_LAKE_PLOT_RAND,
	XML_LAND_IMPROVEMENT,
	XML_LAND_TERRAIN,
	XML_MAX_CITY_DEFENSE_DAMAGE,
	XML_MAX_EXPERIENCE_AFTER_UPGRADE,
	XML_MAX_EXPERIENCE_PER_COMBAT,
	XML_MAX_FORTIFY_TURNS,
	XML_MAX_HIT_POINTS,
	XML_MAX_PLOT_LIST_ROWS,
	XML_MAX_PLOT_LIST_SIZE,
	XML_MAX_REBEL_COMBAT_MULTIPLER,
	XML_MAX_REBEL_YIELD_MODIFIER,
	XML_MAX_WITHDRAWAL_PROBABILITY,
	XML_MIN_CITY_RANGE,
	XML_MIN_CITY_YIELD_DECAY,
	XML_MIN_CIV_STARTING_DISTANCE,
	XML_MIN_EXPERIENCE_PER_COMBAT,
	XML_MIN_TIMER_UNIT_DOUBLE_MOVES,
	XML_MIN_WATER_SIZE_FOR_OCEAN,
	XML_MINIMAP_RENDER_SIZE,
	XML_MISSIONARY_RATE_EFFECT_ON_SUCCESS,
	XML_MISSIONARY_THRESHOLD,
	XML_MISSIONARY_THRESHOLD_INCREASE,
	XML_MOVE_DENOMINATOR,
	XML_NATIVE_GOODS_RAID_PERCENT,
	XML_NATIVE_GROWTH_THRESHOLD_MULTIPLIER,
	XML_NATIVE_TEACH_THRESHOLD_INCREASE,
	XML_NEUTRAL_HEAL_RATE,
	XML_NEW_CITY_BUILDING_VALUE_MODIFIER,
	XML_NEW_HURRY_MODIFIER,
	XML_NO_BAD_GOODIES_EXPERIENCE_PERCENT,
	XML_NO_BAD_GOODIES_GOLD_PERCENT,
	XML_OCCUPATION_CULTURE_PERCENT_THRESHOLD,
	XML_OCCUPATION_TURNS_POPULATION_PERCENT,
	XML_OWNERSHIP_SCORE_DURATION_THRESHOLD,
	XML_OWN_TEAM_STARTING_MODIFIER,
	XML_PEACE_TREATY_LENGTH,
	XML_PEAK_EXTRA_MOVEMENT,
	XML_PEAK_SEE_FROM_CHANGE,
	XML_PEAK_SEE_THROUGH_CHANGE,
	XML_PLAYER_ALWAYS_RAZES_CITIES,
	XML_PLOTS_PER_RIVER_EDGE,
	XML_PLOT_VISIBILITY_RANGE,
	XML_RAZING_CULTURAL_PERCENT_THRESHOLD,
	XML_REBEL_PERCENT_FOR_REVOLUTION,
	XML_REBEL_SENTIMENT_BELLS_FACTOR,
	XML_REBEL_SENTIMENT_TURN_WEIGHT,
	XML_REVOLUTION_EUROPE_UNIT_SHIP_MODIFIER,
	XML_REVOLUTION_EUROPE_UNIT_THRESHOLD,
	XML_REVOLUTION_EUROPE_UNIT_THRESHOLD_INCREASE,
	XML_RIVAL_TEAM_STARTING_MODIFIER,
	XML_RIVER_ATTACK_MODIFIER,
	XML_RIVER_SOURCE_MIN_RIVER_RANGE,
	XML_RIVER_SOURCE_MIN_SEAWATER_RANGE,
	XML_ROUTE_FEATURE_GROWTH_MODIFIER,
	XML_RUINS_IMPROVEMENT,
	XML_SCORE_FATHER_FACTOR,
	XML_SCORE_LAND_FACTOR,
	XML_SCORE_POPULATION_FACTOR,
	XML_SCORE_TAX_FACTOR,
	XML_SEAWATER_SEE_FROM_CHANGE,
	XML_SETTLEMENT_TREASURE_YIELD,
	XML_SHALLOW_WATER_TERRAIN,
	XML_STANDARD_HANDICAP,
	XML_STARTING_DISTANCE_PERCENT,
	XML_TAX_INCREASE_CHANCE,
	XML_TAX_RATE_MAX_INCREASE,
	XML_TAX_TRADE_THRESHOLD,
	XML_TAX_TRADE_THRESHOLD_ATTITUDE_PERCENT,
	XML_TAX_TRADE_THRESHOLD_TAX_RATE_PERCENT,
	XML_TREASURE_UNITCLASS,
	XML_UNIT_PRODUCTION_DECAY_PERCENT,
	XML_UNIT_PRODUCTION_DECAY_TIME,
	XML_UNIT_PRODUCTION_PERCENT,
	XML_UNIT_UPGRADE_COST_PER_PRODUCTION,
	XML_UNIT_VISIBILITY_RANGE,
	XML_WARLORD_EXTRA_EXPERIENCE_PER_UNIT_PERCENT,
	XML_WAR_SUCCESS_ATTACKING,
	XML_WAR_SUCCESS_CITY_CAPTURING,
	XML_WAR_SUCCESS_DEFENDING,
	XML_WAR_SUCCESS_UNIT_CAPTURING,
	XML_WATER_IMPROVEMENT,
	XML_WATER_UNIT_FACING_DIRECTION,

	// the number of XML constants
	// used to set the array length for storage
	NUM_XML_CONSTANTS,
};
// cache XML - end - Nightinggale

#endif	// CVENUMS_h
